### ISSUE TITLE
Trouble using a CatalogReference as Maneuver

### ISSUE THREAD

**Issue by mschneider1711** [pyoscx/scenariogeneration#107]
I am trying to use a CatalogReference of a Maneuver in my OpenSCENARIO Storyboard:

`background_man_group = xosc.ManeuverGroup("Background_Maneuver", maxexecution=100)`

The CatalogReference is created with `breaking_maneuver_ref = xosc.CatalogReference("ManeuverCatalog", "Break_for_Other")`

and is then added to my maneuver group `background_man_group.add_maneuver(breaking_maneuver_ref)`

I get a `TypeError` which says `maneuver input is not of type Maneuver`. However, when I check the add_maneuver method it says it can handle a `xosc.Maneuver` or a `xosc.CatalogRefernce`. Could you please check this?

**Comment by mander76** [comment]
This is not good, I'll check it out

**Comment by mander76** [comment]
Good catch, went through the rest of the code and as far as I can see this was the only place CatalogReference was checked correctly.
Will be available in the next release

**Comment by mschneider1711** [comment]
Thank you very much!
