### ISSUE TITLE
about example:  direct_junctions_entry.py

### ISSUE THREAD

**Issue by qqkkwan** [pyoscx/scenariogeneration#111]
hello ,
In example direct_junctions_entry.py, when i add lane_width=3.5 for first_road,continuation_road and entry_road, the result is inconsistent with expectations. 

the code i changed：
![1654335997814(1)](https://user-images.githubusercontent.com/82800669/171994063-9f2af02e-7d47-4730-9750-dbcda4002c73.png)
and the result:
![image](https://user-images.githubusercontent.com/82800669/171994093-98110787-46ec-4ed1-96b2-a0b68c23d4a4.png)

**Comment by mander76** [comment]
Hmm, it might not be in the release, can you give it a try with the master branch on github?

**Comment by qqkkwan** [comment]
i tried，it does not work?

**Comment by mander76** [comment]
Ok, then I'll try to have a look.

**Comment by mander76** [comment]
Aha, this is in the new_junction_creator branch?

**Comment by qqkkwan** [comment]
sorry, i checkout  new_junction_creator branch and run the ''common_junction_creator.py" . The error is as follows:

 **junction_creator = xodr.DirectJunctionCreator(id=junction_id, name="my direct junction")
AttributeError: module 'scenariogeneration.xodr' has no attribute 'DirectJunctionCreator'**

**Comment by qqkkwan** [comment]
So when will you release the new verison  that i  can update by pip

**Comment by mander76** [comment]
Hopefully soon, but I have some bugs still I wanna take care of.. And for this, I have messed up somewhere with rebaseing, so will have to take a closer look what has gone wrong :(

**Comment by mander76** [comment]
I might have fixed it now (in the new_junction_creator branch), it works for me atleast :)

**Comment by qqkkwan** [comment]
yes, i saw it !

**Comment by mander76** [comment]
V0.8.0 released
