### ISSUE TITLE
OSC2

### ISSUE THREAD

**Issue by MarcosJNS** [pyoscx/scenariogeneration#118]
Awesome work with OSCX, is OpenScenario 2 support coming in the future?

**Comment by tmIdiada** [comment]
Sorry for my interference:

https://github.com/pyoscx/scenariogeneration/issues/80
> Hi, good question. No, not really. Since that is supposed to be a high level scenario description it "should not be needed".
> 
> OpenSCENARIO 1.0 was another story since that is rather low level and xml based, and at that time there was no real way to parametrize and run batch-simulations using OpenSCENARIO (It was introduced in 1.1).
> 
> This was created as a way to actually create OpenSCENARIO 1.0 xmls (then grew to OpenDRIVE aswell), and not sit and write in xml (I would never get my users to do that).
