### ISSUE TITLE
Release v0.9.0 does not include the removal of lib2to3 

### ISSUE THREAD

**Issue by toskyRocker** [pyoscx/scenariogeneration#123]
Please, release a new version of `scenariogeneration` since the `v0.9.0` dated `01-Jul-2022` doesn't contain the latest changes. 
Especially the removal of the `2to3` python lib which solves the crash of the [blender-driving-scenario-creator add-on import](https://github.com/johschmitz/blender-driving-scenario-creator)

**Comment by MandolinMicke** [comment]
That I can fix, forgot about it since it was merged during my vacation. Will fix it today

**Comment by MandolinMicke** [comment]
Done!

**Comment by toskyRocker** [comment]
sure, no prob,  welcome back !
