### ISSUE TITLE
Maybe need to check and add convert_xxx for value

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#124]
Finding In actions.py  maybe other alse have same issue

1. Need to check and add convert_xxx for value
2. add static type like def(speed: float), and use mypy to check

![image](https://user-images.githubusercontent.com/31565799/190884121-7e54c273-4e74-45bc-a083-ed82e23d08c6.png)

**Comment by MandolinMicke** [comment]
Ah, there might be a couple of those left :-(

**Comment by tmIdiada** [comment]
BTW: Don't forget here the line 267 `speed: float`, because can be parameter name/string as well.

**Comment by mander76** [comment]
oh, yeah, the documentation has to be changed everywhere :-/ that I'll fix later when I have time...

**Comment by mander76** [comment]
Those are fixed atleast
Should take a long day and go through all of them..

**Comment by mander76** [comment]
the conversions are now fixed for most of the classes, and fixed the issue with not beeing able to use parameter values for bools
