### ISSUE TITLE
 Does scenariogeneration support converting .xosc file from v1.1 to v1.0 ?

### ISSUE THREAD

**Issue by StephenHU-sh** [pyoscx/scenariogeneration#125]
I want to convert the .xsoc  file from v1.1 to v1.0 .

I'm not sure if it supports such a feature.

Thanks.

**Comment by MandolinMicke** [comment]
If it is compatible it "should work", nice use case actually :)

you could try something like this
`    
    scenario = xosc.Scenario.parse("My_1_1_scenario_file.xosc")
    scenario.header.setVersion(minor=0)
    scenario.write_xml("My_1_0_scenario_file.xosc")
`

**Comment by StephenHU-sh** [comment]
@MandolinMicke 
Thank you very much!
I did what you suggested and it worked.But i have some questions about the conversion.
In the XDS representation, we find that the V1.1 has the "CoordinateSystem" but V1.0 not. But in the two xosc files, i found that cut-in_v1.0.xosc has the "Coordinatesystem" in <StartTrigger>. This contradicts the XDS representation.



![difference in  XSD xosc files](https://user-images.githubusercontent.com/65988728/191159347-5fb3bd9a-05d4-4834-851d-ca36c6205321.png)

![difference in  XSD Representation](https://user-images.githubusercontent.com/65988728/191159287-ee0197d0-6654-4cdc-a99f-a818d149ddd2.png)

**Comment by mander76** [comment]
That seams like a bug, should not be able to happen.. 
Haven't tried using this way actually so half surprised it worked at all :D

**Comment by mander76** [comment]
Hmm, it kind of works for me (still found a bug in the header and will fix it), what version are you using? I'm using the latest 0.9.1

However, my previous example was slighty wrong, should look like this:
`
from scenariogeneration import xosc

scenario = xosc.ParseOpenScenario("multiple_maneuvers.xosc")

scenario.header.setVersion(minor=0)

scenario.write_xml("multiple_maneuvers_0.xosc")`
![image](https://user-images.githubusercontent.com/65649467/191182908-5eb66e2e-4200-48c1-93e7-58cc6d076fc8.png)

**Comment by StephenHU-sh** [comment]
@mander76 
Hi, you are right!
It's ok after using your code.
My previous code like this:
from scenariogeneration import xosc
scenario = xosc.ParseOpenScenario('cut-in.xosc')
scenario.header._revMinor = 0
scenario.write_xml("cut-in_v1.0_4.xosc")
I didn't use the method "setVersion".

**Comment by mander76** [comment]
Ah cool. 
The bug I found I fixed, because the header is still wrong.. Fix is here: https://github.com/pyoscx/scenariogeneration/commit/dd21c5d6f974325dab24bdf788ae00a29809ed64
