### ISSUE TITLE
who to change openscenario version from 1.1 to 1.0?

### ISSUE THREAD

**Issue by zhangzhaobinzzz** [pyoscx/scenariogeneration#126]
The xosc file I generated in v1.1 runs in vtd and has problems. if i change the _MINOR_VERSION=0 in enumerations.py , the following problem will occur: "VehicleCategory.car is not part of OpenSCENARIO V1.1, was prepared in V1.0" How can I change to version 1.0?

**Comment by mander76** [comment]
When you create the Scenario object add the osc_minor_version input

![image](https://user-images.githubusercontent.com/65649467/191663231-050e65e0-a6df-4f6d-a2a8-673bb4cb027c.png)

**Comment by zhangzhaobinzzz** [comment]
I still don't know where the interface is. Can you give me an example？

**Comment by mander76** [comment]
sce = xosc.Scenario('curvature test','Mandolin',paramdec,entities=entities,storyboard = sb,roadnetwork=road,catalog=catalog,osc_minor_version=0)
