### ISSUE TITLE
Extend common junction creator to accept arbitrary connecting road geometries

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#127]
I am wondering if it would be easily possible to extend the common junction creator to optionally accept self defined connecting road geometries. Something like this
```

junction_creator.add_connection(road_one_id = 1, 
                                road_two_id = 3, connecting_road=my_connecting_road)
```
instead of just this

```
junction_creator.add_connection(road_one_id = 1, 
                                road_two_id = 3)
```
This would be the missing piece for usage in a GUI tool I think.

**Comment by MandolinMicke** [comment]
hmm so you mean that you have created my_connecting_road yourself?

**Comment by johschmitz** [comment]
Yes, exactly like you say, a matching connecting road needs to be provided.
Regarding the lanes I am a bit unsure but I think the default needs to be to connect all lanes to each other. For some cases though where only a single lane (or small number of lanes, like sidewalk) connecting road is used then it needs to be possible to specify on both ends which lane(s) to connect to.

**Comment by mander76** [comment]
I have made a first try in this branch: https://github.com/pyoscx/scenariogeneration/tree/junction_creator_with_own_road

It cannot handle roads with different amount of lanes (added an example for this simple example as well examples/xodr/common_junction_with_self_made_connecting_road.py)

**Comment by mander76** [comment]
@johschmitz Have you tried the fix?

**Comment by johschmitz** [comment]
I am currently using the low level interface and wrote my own code based on that and did not have time to test this. Not sure if I will get to this anytime soon but I think it is definitely helpful for people starting from scratch and directly using the API who want to have some control over the connecting road and what is going on with the traffic on the junction. I might revisit this when I implement connecting roads with 3 geometries (arc - clothoid - arc or clothoid - clothoid - clothoid) instead of only one (clothoid) and I also wanted to look into some tool which does each connecting road as a single lane or so. The thing is there are so many other things in my backlog I am not sure when I will get to this.

Just looking at the example in 
https://github.com/pyoscx/scenariogeneration/compare/main...junction_creator_with_own_road
the API looks fine to me though. I would say you could go ahead, merge it and close the ticket for now. I also suggest to add at least one additional connection to the example and see if that works before you merge it, just to be on the safe side.

**Comment by johschmitz** [comment]
I just had a discussion and was wondering if we could build this example from the standard with this feature:

![image](https://user-images.githubusercontent.com/771979/226194537-237e747b-f752-4f06-88bf-c3822c51144f.png)

@mander76 what do you think? Or can this even be done without this feature? I think one might need lane offset to properly construct this juntion.

**Comment by mander76** [comment]
This should be enabled with the junction creator. I haven't done one with 6 lanes in each road, but enough to think that it should work without any addition.

This example should suffice I think
https://github.com/pyoscx/scenariogeneration/blob/main/examples/xodr/common_junction_creator.py

**Comment by johschmitz** [comment]
Hm, but how do you do the lane offset and linking to only a certain lane? For example the one from -3 to 3. Is that possible?

**Comment by mander76** [comment]
yes, as in the example
```
junction_creator.add_connection(
    road_one_id=1, road_two_id=2, lane_one_id=2, lane_two_id=1
)
```
where the lanes inputs are connecting only that lane
