### ISSUE TITLE
ParameterDeclaration in Controller is 0..*, but raise AttributeError

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#131]
Whether in version 1.0 or 1.1, ParameterDeclaration can be left unset，but i got an AttributeError “'NoneType' object has no attribute 'findall'” 

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/31565799/194760365-c5e2bcd7-27f5-421d-8b8b-19d5778fbf23.png">

**Comment by dongfeng2134** [comment]
i just change like this, it work
<img width="908" alt="image" src="https://user-images.githubusercontent.com/31565799/194760663-4dd61e1f-b8c6-4824-b5b9-507720bea8eb.png">

**Comment by mander76** [comment]
Feel free to do a pull request with this change if it works :)
