### ISSUE TITLE
How to change openscenario version from 1.1 to 1.0 when parse xosc file?

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#132]
Try below method, is not working

![image](https://user-images.githubusercontent.com/31565799/194791320-d8f68207-c714-4a49-835c-346be848ef39.png)

**Comment by mander76** [comment]
https://github.com/pyoscx/scenariogeneration/issues/125 some things were changed in relation to this, can you try with master (see that I haven't done a release) 
Please confirm that it works, and I'll make a new release.
