### ISSUE TITLE
Missing some useful condition such as relativeClearenceCondition and variableCondition.

### ISSUE THREAD

**Issue by SamsonLu** [pyoscx/scenariogeneration#134]
It seems that not all the conditions that conform to the openscenario 1.0 standard are defined in the trigger.py file. For  example the relativeClearanceCondition which is often used in lane changing scenarios, as well as other conditions.
![relativeclearance](https://user-images.githubusercontent.com/48321801/196877838-614eb550-adf6-42b4-bdf3-135fb6fc9bdd.png)

**Comment by mander76** [comment]
RelativeClearanceCondition is not part of OSC1.0, but OSC1.2.

I haven't finished the 1.2 implementation yet (have been very busy), but that one is implemented and you can try it out on the branch
https://github.com/pyoscx/scenariogeneration/blob/update_to_1_2/scenariogeneration/xosc/triggers.py

**Comment by mander76** [comment]
Now OpenSCEANARIO V1.2 is supported and in master, including RelativeClearanceCondition,
