### ISSUE TITLE
class _OscEnumReturns the Enum member in cls matching name in enumerations.py -> class _OscEnum

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#136]
Returns the Enum member in cls matching name in enumerations.py -> class _OscEnum

As shown below
<img width="805" alt="image" src="https://user-images.githubusercontent.com/31565799/200522994-1954cc45-d699-4c00-880d-92577138aa2f.png">
https://docs.python.org/3/library/enum.html#programmatic-access-to-enumeration-members-and-their-attributes

**Comment by mander76** [comment]
So you wanna do something like this?
ConditionEdge["falling"] ?

**Comment by mander76** [comment]
please try out this branch: https://github.com/pyoscx/scenariogeneration/tree/new_enum_functionally

**Comment by mander76** [comment]
good, then I*ll merge it
