### ISSUE TITLE
Only info - no action required: Presentation at ASAM Conference this November

### ISSUE THREAD

**Issue by jakobkaths** [pyoscx/scenariogeneration#137]
Hi everybody and especially @mander76 and @MandolinMicke, @inatale93 as authors,

I'm not sure if an issue is the best way to do this, but I just wanted to mention that I will present at the ASAM Conference in a few weeks in Dresden, Germany. I will show something around the topic of re-usability of scenarios and I will make use of scenariogeneration to generate OpenDRIVEs automatically with parameters. For sure I will mention the worth of this package. Maybe I gain a few contributors or at least users. :-)

Best regards

Jakob

**Comment by mander76** [comment]
Cool! 
I wanted to join, but didn't get ok from work :( I'll tell Emil Knabe to go and listen ;)

**Comment by jakobkaths** [comment]
Sounds good!
