### ISSUE TITLE
Whether to consider improving the speed of generating files？

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#138]
Whether to consider improving the speed of generating files
Especially when generating a large number of files, such as more than 100000, it will be very time-consuming

**Comment by mander76** [comment]
Yes, I'm painfully aware. 

One way is to use the "ParameterValueDistirbution" from OSC 1.1, and use that definition instead. 

I came into this problem myself the other week, and started to look into if ScenarioGenerator could be parallelized somehow.. Sadly that is not possible without major refactoring of that class.

**Comment by mander76** [comment]
Took another look now actually and kind of solved it!

It's not the perfect solution, but generating 50000 scenarios I cut the time with 30% from 6 sec to 4 sec (running 8 parallel processes for writing the files)
Will commit shortly

**Comment by mander76** [comment]
checkout this one if you have a usecase: https://github.com/pyoscx/scenariogeneration/tree/parallelization_of_writings
