### ISSUE TITLE
xosc 1.0.0 is missing "Private" class

### ISSUE THREAD

**Issue by Dragonking3x** [pyoscx/scenariogeneration#139]
I am currently working on creating an OpenScenario v1.0.0 file and testing this package.

In the Documentation is a "Private" entry before "PrivateAction"
https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/index.html

![image](https://user-images.githubusercontent.com/16963388/204805161-667bc8e6-a1ba-411e-ac82-f00453d66329.png)

```
<Storyboard>
  <Init>
    <Actions>
      <Private entityRef="adversary">
        <PrivateAction>
          <TeleportAction>
            <Position>
              <RelativeRoadPosition entityRef="hero" ds="50" dt="0.0"/>
            </Position>
          </TeleportAction>
        </PrivateAction>
      </Private>
    </Actions>
  </Init>
</Storyboard>
```

I can't find a "Private" class and it looks like the "scenariogeneration.write_xml()" function is ignoring the version.
```
    sce = xosc.Scenario(
        "testing",
        "User",
        paramdec,
        entities=entities,
        storyboard=sb,
        roadnetwork=road,
        catalog=catalog,
        osc_minor_version=0
    )
    sce.header.version_minor = 0
    sce.write_xml("../temp/test.xosc")

```
```
<Storyboard>
  <FileHeader description="testing" author="User" revMajor="1" revMinor="0" date="2022-11-30T14:07:05.768376"/>
  <Init>
    <Actions>
      <PrivateAction>
        <TeleportAction>
          <Position>
            <RoadPosition roadId="105" s="48.58" t="2.0"/>
          </Position>
        </TeleportAction>
      </PrivateAction>
    </Actions>
  </Init>
</Storyboard>
```

I shorted the text to only have the important parts.

**Comment by mander76** [comment]
Hmm, interesting, I don't have that behavior... Should not have to do with the version, since that haven't changed between OSC versions. 
Can you provide a code snippet how you create the Init and the Action?

**Comment by mander76** [comment]
You are setting a user_defined_action, which sets a user_definedAction not a private action

so you need to use
init.add_init_action(egoname,init_private_action_ego())
not
init.add_user_defined_action(init_private_action_ego())

**Comment by Dragonking3x** [comment]
ah
That makes sense.
It works now.
Thank you.
