### ISSUE TITLE
How to find the lane id of the road

### ISSUE THREAD

**Issue by S1201149** [pyoscx/scenariogeneration#14]
Hello,
I am trying to use the .xodr files present in the examples folder of this project in my python code for scenario generation.
I want to use the road infrastructure created from the xodr file. But I am not able to position the entities in the road created.
Is there any way to find the lane id? (From the details mentioned in Lane.py I got to know that lane id is generated automatically)
Please find the attached log for error details.
[log.txt](https://github.com/pyoscx/scenariogeneration/files/6318129/log.txt)

I have attached my python code for more clarity. Kindly help me with this and let me know am I doing the right thing.
My python code works fine with the .xodr files shown in python examples of this project. ( Got to know the lane id from examples shown). I am finding difficulty in using other .xodr files and I am struck with this issue.
(Attaching python code as txt file as python file is not supported here)
[slowpreceding_curvedroad.txt](https://github.com/pyoscx/scenariogeneration/files/6318253/slowpreceding_curvedroad.txt)

**Comment by eknabevcc** [comment]
As you state, the road ID need to match roads available in the road network. In this case, in the example xodr the road is assigned id = 1. 
That's something you simply need to check, e.g. open the OpenDRIVE file in an editor and look for the line(s):
`<road id="1" junction="-1" length="500">`
So in this case you can change your LanePositions to refer to Road ID = 1 and perhaps lane ID = -1 (first lane on right side of center/ref line).
See attached edited scenario.
[slowpreceding_curvedroad-edit.txt](https://github.com/pyoscx/scenariogeneration/files/6318350/slowpreceding_curvedroad-edit.txt)
By the way, the order of parameters for LanePosition you can find [here](https://pyoscx.github.io/xosc/position.html#scenariogeneration.xosc.position.LanePosition).

**Comment by mander76** [comment]
Hello

This is a tricky part (sadly), but the tedious way is to read the xml (manually), this I don't recommend for further development.

What I would do is to use the ScenarioGenerator class (eg examples/generator/generate_with_fixed_parameter_sets.py), where you both generate the road and the scenario at the same time.
Then you can either set the lane/road id as parameters, or just as a attribute of the class, then you know for sure that you will have the same ids. 
below you can see a simplified example of one way of doing it (not the entire scenario written out)

```

class Scenario(ScenarioGenerator):
    def __init__(self):
        ScenarioGenerator.__init__(self)

        self.naming = 'numerical'
        self.road_id = 1

        
    def road(self,**kwargs):

        road = xodr.generators.create_straight_road(self.road_id, length=100, junction=-1, n_lanes=2, lane_offset=3))

        odr = xodr.OpenDrive('myroad')
        odr.add_road(road)
        
        odr.adjust_roads_and_lanes()
        return odr
        
    def scenario(self,**kwargs):
        road = xosc.RoadNetwork(self.road_file)


        init = xosc.Init()


        init.add_init_action(egoname,xosc.TeleportAction(xosc.LanePosition(50,0,-1,self.road_id)))
        # the rest of your scenario    
        return scenario

```

**Comment by S1201149** [comment]
> As you state, the road ID need to match roads available in the road network. In this case, in the example xodr the road is assigned id = 1.
> That's something you simply need to check, e.g. open the OpenDRIVE file in an editor and look for the line(s):
> `<road id="1" junction="-1" length="500">`
> So in this case you can change your LanePositions to refer to Road ID = 1 and perhaps lane ID = -1 (first lane on right side of center/ref line).
> See attached edited scenario.
> [slowpreceding_curvedroad-edit.txt](https://github.com/pyoscx/scenariogeneration/files/6318350/slowpreceding_curvedroad-edit.txt)
> By the way, the order of parameters for LanePosition you can find [here](https://pyoscx.github.io/xosc/position.html#scenariogeneration.xosc.position.LanePosition).

Hello @eknabevcc ,
Thanks for the reply! I tried the edited script. It works. 
If Road ID = 1 and lane ID = -1 (first lane on right side of center/ref line). what will be the lane id of the left lane to the centerline?
I tried with values like 0,1,-2 etc, but nothing works. Could you help me with this

**Comment by S1201149** [comment]
> Hello
> 
> This is a tricky part (sadly), but the tedious way is to read the xml (manually), this I don't recommend for further development.
> 
> What I would do is to use the ScenarioGenerator class (eg examples/generator/generate_with_fixed_parameter_sets.py), where you both generate the road and the scenario at the same time.
> Then you can either set the lane/road id as parameters, or just as a attribute of the class, then you know for sure that you will have the same ids.
> below you can see a simplified example of one way of doing it (not the entire scenario written out)
> 
> ```
> 
> class Scenario(ScenarioGenerator):
>     def __init__(self):
>         ScenarioGenerator.__init__(self)
> 
>         self.naming = 'numerical'
>         self.road_id = 1
> 
>         
>     def road(self,**kwargs):
> 
>         road = xodr.generators.create_straight_road(self.road_id, length=100, junction=-1, n_lanes=2, lane_offset=3))
> 
>         odr = xodr.OpenDrive('myroad')
>         odr.add_road(road)
>         
>         odr.adjust_roads_and_lanes()
>         return odr
>         
>     def scenario(self,**kwargs):
>         road = xosc.RoadNetwork(self.road_file)
> 
> 
>         init = xosc.Init()
> 
> 
>         init.add_init_action(egoname,xosc.TeleportAction(xosc.LanePosition(50,0,-1,self.road_id)))
>         # the rest of your scenario    
>         return scenario
> ```

Hello @mander76 ,
Thank you for your response!
With this class method one cannot use the xodr files that are created.
Only with the help of this function we can create road  ### " road = xodr.generators.create_straight_road(self.road_id, length=100, junction=-1, n_lanes=2, lane_offset=3))"
Is my understanding correct?
Even with the examples under generator folder I couldn't get how they are determining the lane id

**Comment by MandolinMicke** [comment]
Ah, the lane ids are the same as @eknabevcc  described, (you can see the opendrive documentation for more info), but in short, negative to the right, positive to the left.

**Comment by eknabevcc** [comment]
As @MandolinMicke states, positive lane ID's on right side of road construction direction. And negative to the left. Counting from center lane 0. 
In your specific file you have only two lanes to the right of "center line" (a bit strange perhaps to call this center since it's the left boundary - maybe better to call it "reference line". Normally, when you have lanes in both directions, this reference line is in center). Anyway, the options you have, in this case, in terms of lane ID are: -1 and -2.
You can test attached script which put red car in -1 and Ego in -2.
[slowpreceding_curvedroad-edit2.txt](https://github.com/pyoscx/scenariogeneration/files/6320796/slowpreceding_curvedroad-edit2.txt)

**Comment by S1201149** [comment]
Hello,
Here, I have attached my own xodr file generated using python code. Here the left lane id is 1 and the right lane id is -1.
The entities I created works fine in the right lane. But if I change the lane id to 1(left lane) the entities don't behave as expected. I have attached my python code as well. 
[slowpreceding.txt](https://github.com/pyoscx/scenariogeneration/files/6322534/slowpreceding.txt)
[curved_road_xodr.txt](https://github.com/pyoscx/scenariogeneration/files/6322537/curved_road_xodr.txt)

**Comment by mander76** [comment]
without running, it should be that with lane id -1 the car is driving along the road and have alot of road to drive on, with lane id 1 the car starts very close to the end of it's lane. 
Remember that the first input to the lane position is "s" which is the along road coordinate. Hence on the right side of the road (negative lane index) the car will run along s (increase s while driving), and on the left side of the road (positive lane index) the car will run against s (decrease while driving).

**Comment by S1201149** [comment]
Hello @mander76,
Is it possible to change the behaviour of the right side road to the left side and left side road to the right?  
To be more specific increasing s while driving in the left lane and decreasing s while driving in the right lane. Is it possible to do with the code?

**Comment by eknabevcc** [comment]
What you can do is to put your vehicles in "the wrong direction". So for example, Ego in the left lane (-1), at the beginning of the road (low s), but turned 180 degree (pi). And the red car in the other lane (+1), at end of road (high s), also turned 180 deg.
Please check and test attached script.

[left-hand-traffic.txt](https://github.com/pyoscx/scenariogeneration/files/6323548/left-hand-traffic.txt)

(there will be a "left hand traffic" flag, but it's not supported yet, that's why you need to explicitly turn the vehicle around)

**Comment by S1201149** [comment]
Hi,
Thanks for the input!
Is it possible to create two way traffic in a single lane road. (To create a rural road scenario)?

**Comment by mander76** [comment]
personally I would create one left and one right lane, but half the roadwith, then leave the centerlane without a lanemarker

**Comment by johschmitz** [comment]
I just read the last comment about two half lanes. @mander76  do you really think that is a good idea? My approach till now was to just add a single right lane. I hope that will work fine.

**Comment by MandolinMicke** [comment]
It can probably be done on multiple ways, and slightly depending on the simulator, and how it handles directions.
