### ISSUE TITLE
TimeOfDay animation "False" instead of "false"

### ISSUE THREAD

**Issue by Dragonking3x** [pyoscx/scenariogeneration#141]
The Class
scenariogeneration.TimeOfDay(False, 2022,12, 5, 12, 00, 00)
will generate 
<TimeOfDay animation="False" dateTime="2022-05-26T10:00:00"/>
The "False" should be "false"

This is a problem for scenario_runner (Carla Simulator).
Changing it to 
<TimeOfDay animation="false" dateTime="2022-05-26T10:00:00"/>
manually fixes the problem

**Comment by atingber** [comment]
Issue #141 has been resolved
