### ISSUE TITLE
OverrideControllerValueAction not support OSC v1.0.0

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#143]
In Osc 1.0.0 this is 1..1

https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/OverrideControllerValueAction.html
<img width="968" alt="image" src="https://user-images.githubusercontent.com/31565799/206459089-157f4618-77bf-4df6-beba-70735e76a069.png">

**Comment by mander76** [comment]
you can still add all?

**Comment by dongfeng2134** [comment]
All right, I got it
