### ISSUE TITLE
Get unexpected characters in the generated xosc file

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#144]
use UserDefinedAction & CustomCommandAction to set user action with **">"**
![image](https://user-images.githubusercontent.com/31565799/206633263-c7d06c04-f5cb-4936-92f0-10812e6009ed.png)

I will got **&gt;** in xosc file
![image](https://user-images.githubusercontent.com/31565799/206633392-44b8fc66-c2ad-4418-b2d5-382aafbb90d8.png)

**Comment by dongfeng2134** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/31565799/206634925-c86397de-bf42-4ac2-af2c-5575eeb8955f.png">

**Comment by MandolinMicke** [comment]
Hmm, I have seen this issue with xml and strings before. 
I had a similar issue a couple of months ago , have to try to dig out where I did those things.

**Comment by dongfeng2134** [comment]
> My examples still have those but still work (I run with esmini)

Fine，but some business simulation software is not supported yet

**Comment by mander76** [comment]
Top two searches:

https://docs.oracle.com/cd/A97335_02/apps.102/bc4j/developing_bc_projects/obcCustomXml.htm
https://dvteclipse.com/documentation/svlinter/How_to_use_special_characters_in_XML.3F.html

Looks like your development team might have to update the xml lib they are using.

**Comment by dongfeng2134** [comment]
ok, got it

**Comment by dongfeng2134** [comment]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/31565799/232208525-cd804bf6-1b4a-4ef5-a1f1-c5e2002d4368.png">

**Comment by dongfeng2134** [comment]
![Uploading image.png…]()

**Comment by mander76** [comment]
Please Chech https://github.com/pyoscx/scenariogeneration/tree/encoding
