### ISSUE TITLE
The content is missing in CustomCommandAction

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#146]
https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/CustomCommandAction.html
![image](https://user-images.githubusercontent.com/31565799/207645117-4eda8b96-2aaa-45b7-bf35-4e1074acf10b.png)

![image](https://user-images.githubusercontent.com/31565799/207645208-aaa20285-d29b-474b-8d53-56049bdab089.png)

**Comment by dongfeng2134** [comment]
Please take a look at this question

**Comment by mander76** [comment]
I'm honestly not sure how it should look, what is the content? it's not an attribute? so what is it?

**Comment by dongfeng2134** [comment]
![image](https://github.com/pyoscx/scenariogeneration/assets/31565799/04f5a257-e08d-4172-92bc-422edf3af3eb)

**Comment by mander76** [comment]
cool, will try

**Comment by mander76** [comment]
I have a solution on the branch https://github.com/pyoscx/scenariogeneration/tree/custom_command_action_fix

I changed the api, since I realized that the add_custom_command method was unnecessary since one UserDefinedAction only can have one custom command.

HAve a look, and I'll merge later when you tested it and the tests has passed.

**Comment by dongfeng2134** [comment]
![image](https://github.com/pyoscx/scenariogeneration/assets/31565799/07775825-f83d-40f3-9dd0-f9586ae49fd7)

It's working, thanks to work

**Comment by dongfeng2134** [comment]
It's working, thanks to work
![image](https://github.com/pyoscx/scenariogeneration/assets/31565799/03c61803-4205-4ca7-a543-b71335fb073f)

**Comment by mander76** [comment]
New release with this implementation release. Closing issue
