### ISSUE TITLE
create_junction_roads() based on incoming road IDs

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#15]
The generator function create_junction_roads() expects a list of incoming roads as a parameter which is shown in the example:
https://github.com/pyoscx/scenariogeneration/blob/main/examples/xodr/junction_with_signals.py
Creating this list is troublesome and it would be way easier to provide the list of road IDs instead it seems.
Could this be changed or a second method be added?
What was the original reason for the API design like this?

Should be:
`def create_junction_roads(road_ids, angles, r, junction=1, spiral_part=0.3333333333333333, arc_part=0.3333333333333333, startnum=100)`

It seems a workaround is to first find the roads with get_road_by_id() but why not just provide the ID to create_junction_roads() and let is do the work? At least there is a workaround so this is not critical but also not very nice. Road IDs and Python references should be decoupled in the API. If the user already handles the IDs he should not have to handle the references. Or is there a valid reason for this?
A similar case seems to be the create_lane_links() method.

**Comment by johschmitz** [comment]
Now that I am fully using this it feels even more complicated. I first have to build up a complete list of all my roads then for each junction give that huge list to get_road_by_id. Very inefficient and not easily possible to create any junction before having created all roads :|

**Comment by mander76** [comment]
get_road_by_id still requires a list of roads, and we cannot find the required roads in another workspace. So finding the roads is kind of impossible. 
Why the list is needed has 2 main reasons.
1. To create the junction roads, more info than the ids of the incoming roads are needed (like number of lanes)
2. The input list of roads are changed (successor and predecessor are added)

It should not be a big issue to create a junction without the incoming roads, using the IDs as you say (but if you haven't created a road you still need to know its ID) , and you have to add the number of lanes as input. 

However you don't add the IDs to the method (like if you don't have created the road yet), you have to handle **ALL** successors/predecessors in the generated roads yourself (will not be fun either). 

Remember that the create_junction_roads is a simple function for prototyping quickly from a script, it is not ment (at least now) to be a generic function to generate junction roads, that is a much bigger task, and will probably require that you know the rest of the roads already placed. 
If this is for your graphical interface, I would suggest to do a very similar function that just generates the junction roads (thats just a simple loop you can find in create_junction_roads), and then take care of the linking afterwards.

**Comment by johschmitz** [comment]
Okay I now see your bigger picture view. I am wondering if it would then be possible to call create_junction_roads() without specifying incoming roads at all and later when connecting the roads to the junction create the connections. Would that simplify or complicate things?

I think in general I need to further implement everything and release a v0.1.0 of my tool to let you play with it and then it will make discussing a lot easier.

**Comment by mander76** [comment]
That should be a rather simple function to write, I can try to lookinto it tonight, it will probably be a different function though (since the input will be quite different).

Would be nice to test your tool out :) Luckily I know what you are doing so I see why you have issues, since these "generators" are especially made for "non gui" applications :P

**Comment by MandolinMicke** [comment]
added create_raw_junction_roads to fulfill this. Will do a push to pipy tomorrow aswell to create a new version.

**Comment by johschmitz** [comment]
@MandolinMicke Could you instead call it
create_junction_roads_open
create_junction_roads_no_incoming
or something that makes clear from the name what it does? Raw could mean many different things..
In any case put it as a postfix so that we have alphabetical/hierarchical ordering in the documentation etc. !
create_junction
create_junction_roads
create_junction_roads_raw

**Comment by mander76** [comment]
sure, now it's called _standalone
