### ISSUE TITLE
How can I  modify the trigger info  in  openSCENARIO file ?

### ISSUE THREAD

**Issue by StephenHU-sh** [pyoscx/scenariogeneration#150]
Hello ,

When building  a new scenario,  the starttrigger details must be provided.  But now, I want to modify the "starttrigger" in the scenario file . For example , i want to reset the conditionEdge to "falling", and reset the rule to "lessThan". 

How can i do it ? I can't get the access to get the details and change it .

I look forward to hearing from you soon.

![image](https://user-images.githubusercontent.com/65988728/217440596-0c10efdc-909a-44bd-b468-fd50edb5c84f.png)

![image](https://user-images.githubusercontent.com/65988728/217441458-9b3a2f60-f8f4-4cb9-b927-e425a422c111.png)

![image](https://user-images.githubusercontent.com/65988728/217441788-a3a5bc92-917b-488b-99ff-c6f71298a278.png)

**Comment by mander76** [comment]
Hi

As I understand it you want to edit an exsisting xosc? 
Don't know what xoscParse is? It's not part of this package. 

In scenariogeneration there is a ParseOpenScenario function that will return the Scenario object. 
So maybe something like this (if it is the trigger in the act) (to change the conditionEdge)

```
from scenariogeneration import xosc
sce = xosc.ParseOpenScenario(filename)

sce.storyboard.stories[0].acts[0].starttrigger.conditiongroups[0].conditions[0].conditionedge = xosc.ConditionEdge.falling

sce.write_xml(filename)

```
There you have the acts condition , assuming you only have one story and one act (otherwise just change the indexes)

Good luck

**Comment by StephenHU-sh** [comment]
Dear,

Thanks for your advice, it's useful.   But I have new problem. Details as bellow:

The existing xosc just have only one condition in each conditiongroup. i want to add a new one . the new condition is very similar to the old one . For this , I add a same one to the conditiongroup and reset some parameters of the new condition.
code like these:
`conditiongroups = event.trigger.conditiongroups[0]
  copycondition = condition
  conditiongroups.add_condition(copycondition)
new_condition = conditiongroups.conditions[1]
new_condition.entitycondition.value = 11.11   # i want the change the value.
`

But some problems here. 
1. after changing the new condition , the old condition changed also.  the root reason is that the 2 conditions has same memory address.   why ?

![image](https://user-images.githubusercontent.com/65988728/217499174-3c00ee88-ebe9-4170-a4f5-10f59082c6ba.png)

2. i can't use copy or deepcopy to avoid the problem.

**Comment by mander76** [comment]
Why can't you use copy?

**Comment by StephenHU-sh** [comment]
@mander76 
I made a mistake , deepcopy is ok .

Thanks very much!
