### ISSUE TITLE
Expect to support more enum features in xosc enumerations.py 

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#156]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/31565799/227771696-7f3ae1bc-8ca2-48ab-9357-f51394a8542c.png">

**Comment by mander76** [comment]
try xosc.Rule.get_name()

**Comment by dongfeng2134** [comment]
![image](https://user-images.githubusercontent.com/31565799/227854183-76f09192-675c-4ebe-ac73-d78c677b3672.png)

**Comment by dongfeng2134** [comment]
class ExtendedEnum(Enum):
    @classmethod
    def values(cls):
        return list(map(lambda c: c.value, cls))

    @classmethod
    def values_re(cls):
        return "|".join(map(lambda c: str(c.value), cls)).strip("|")

    @classmethod
    def names(cls):
        return list(map(lambda c: c.name, cls))

    @classmethod
    def names_re(cls):
        return "|".join(map(lambda c: str(c.name), cls))

    @classmethod
    def dict(cls):
        return {c.name: c.value for c in cls}

    @classmethod
    def mulitvalue_get_(cls, arg):
        values = list(sum(cls.values(), ()))
        idx = values.index(arg)
        return cls((values[idx - 1], values[idx])) if idx & 1 else cls((values[idx], values[idx + 1]))

    @classmethod
    def mulitvalue_get(cls, arg):
        for mulitvalue in cls.values():
            if arg in mulitvalue:
                return cls(mulitvalue)

**Comment by mander76** [comment]
is it a list of all enums you want?

**Comment by mander76** [comment]
[x for x in xosc.Rule.__dict__.keys() if '__' not in x]
