### ISSUE TITLE
osc 1.0 model3d parse error when define model3d in Property

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#161]
OpenSCENARIO 1.0.0
if define define model3d in Property
<img width="432" alt="image" src="https://user-images.githubusercontent.com/31565799/233790938-8b14b604-d76e-4733-a2e7-3695e2ace18f.png">

Will got error ”model3d of a vehcile was introduced in OSC 1.1“

<img width="878" alt="image" src="https://user-images.githubusercontent.com/31565799/233790970-f821e937-013a-4183-802e-fa21af963e94.png">

**Comment by mander76** [comment]
can you provide the full Vehicle xml that fails (as text not picture)?

**Comment by mander76** [comment]
Not sure what the problem is, I parse it and can convert to both 1.0,1.1 ad 1.2?

```
from scenariogeneration import xosc, prettyprint
import xml.etree.ElementTree as ET

filename = 'vehicle_test.xml'

with open(filename, "r") as f:
    vehicle_element = ET.parse(f).find("Vehicle")

veh = xosc.Vehicle.parse(vehicle_element)
veh.setVersion(minor=2)
prettyprint(veh)
```

**Comment by dongfeng2134** [comment]
just parse xosc file， Not related to the simulator

Ps. i use my own private simulator
below is my  private definition，  without changing it， how to correctly parse XOSC files
<Property name="model3d" value="sedan/sd01.fbx"/>

**Comment by dongfeng2134** [comment]
The question raised was incorrect, so it was closed
