### ISSUE TITLE
Will got error when bounding_box=None in class Fog 

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#163]
![image](https://github.com/pyoscx/scenariogeneration/assets/31565799/d452e686-67ff-468c-8314-a4c70f3a5303)

**Comment by mander76** [comment]
Nice catch

fix available here: https://github.com/pyoscx/scenariogeneration/tree/fog_fix

**Comment by unitzze** [comment]
Seems like this fix was somehow lost in the latest release (0.13.1) as the same error shows up.

Also, when generating OSCV1.1 it is possible to set fog=None, however when generating OSCV1.0 it is required to define fog. 
"raise OpenSCENARIOVersionError("In OpenScenario 1.0, Fog is required.")"

**Comment by mander76** [comment]
Well, that's most probably because I haven't mad a release yet :-/ Will try to fix it this week.

**Comment by mander76** [comment]
New release available
