### ISSUE TITLE
OpenDRIVE lane linking issue

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#169]
I reported a problem here https://github.com/esmini/esmini/issues/447 and @eknabe correctly told me that some links where missing. I then further investigated the problem and found that 
```
xodr.create_lane_links_from_ids(road, road_suc, lane_ids_road, lanes_ids_road_suc)
```
is failing for this edge case where the road is connected to a junction and another road.

![image](https://github.com/pyoscx/scenariogeneration/assets/771979/c817edb4-bbd7-4654-a0af-bf9e3e5d01f7)

Deeper debugging showed that there seems to be a bug in
```
 _get_related_lanesection(road1, road2)
```
https://github.com/pyoscx/scenariogeneration/blob/484656b8f8a2387f3ce3072a0fa303a424c9a749/scenariogeneration/xodr/links.py#L864

It first correctly identifies the `linktype` as `successor` but then overwrites it since it also finds the junction connected to the other end.

**Comment by johschmitz** [comment]
I created a pull request to fix this problem. Please check if this makes sense.

**Comment by mander76** [comment]
This fails a bunch of tests, so not a viable solution sadly enough.

**Comment by mander76** [comment]
I created a simple example to replicate the issue [circular_road_with_junction.zip](https://github.com/pyoscx/scenariogeneration/files/11981591/circular_road_with_junction.zip)
And found out the real problem, and pushed a fix to this branch: https://github.com/pyoscx/scenariogeneration/tree/circular_road_with_junction_fix
Could you try it out and see if it solves it for you aswell?

**Comment by johschmitz** [comment]
@mander76 I can confirm that this works. Please merge and release.
