### ISSUE TITLE
Which radius is meant in junction road generator?

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#17]
In the documentation it says:

https://github.com/pyoscx/scenariogeneration/blob/16d597e6fdd827168dd3c1a336d0df77aae3d7c7/scenariogeneration/xodr/generators.py#L311

Is this the inner or outer or centerline radius? Maybe you should add a sentence like, "e.g., a radius of 4 creates a 4 by 4 m junction."

If I am going to find out before you answer and fix this I am going to submit a pull request, just need to reach the point where I can use esmini in any sensible way ;-)

**Comment by mander76** [comment]
Actually what is says, the arcs radius, since a turn is composed of an clothoid-arc-clothoid.

**Comment by mander76** [comment]
But my colleague is actually working on this, to make it more generic (not only 90 deg crossings)

**Comment by pyoscx** [comment]
Check the latest commit, not in pip yet, but there a new implementation is done for how to generate the roads with the radius as a input
