### ISSUE TITLE
How to generate xosc file for carla scenario runner

### ISSUE THREAD

**Issue by hiber-wang** [pyoscx/scenariogeneration#175]
Hello,  I would like to extend my heartfelt appreciation for the exceptional work you've been doing.

I have a query that I'd like to kindly ask: do you happen to be knowledgeable about the process of utilizing scenariogeneration to generate xosc files for the Carla Scenario Runner? If you could provide some basic examples, I would be immensely grateful for your guidance. Thank you very much for your assistance.

**Comment by mander76** [comment]
> Hello, I would like to extend my heartfelt appreciation for the exceptional work you've been doing.
Thanks :)

I personally haven't used Carla myself, but there has been a couple of issues about it.
https://github.com/pyoscx/scenariogeneration/issues/62
https://github.com/pyoscx/scenariogeneration/issues/149

The main thin (as far as I know) is to use OSC version 1.0, so be sure to add
osc_minor_version to your scenario constructor

`sce = xosc.Scenario( "lane change", "Arjun", paramdec, entities=entities, storyboard=sb, roadnetwork=road, catalog=catalog, osc_minor_version=0 )`

Good Luck
