### ISSUE TITLE
Error when trying to run esmini

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#18]
I have downloaded esmini and installed to `/opt` which is basically the most common way to manage third party software that is not managed by the package manager on Linux.
When trying to run esmini I am getting an error like this:
`Not a directory: '/opt/esmini/bin/esmini/resources/xosc/python_scenario.xosc'`
It seems you are trying to generate the output of the scenariogeneration lib into the esmini install folder.
I would say this is not a clean way of managing the data. You can in general not assume to have write access to a software install folder, neither on Linux nor Windows or Mac.
May I suggest to let the user configure the ressource path and default this path to
`/tmp/scenariogeneration` on Linux/Mac
and
`C:\Users\<username>\AppData\Local\Temp` on Windows?
to avoid errors like the above one in the future?

**Comment by johschmitz** [comment]
Now that I thought about it more maybe an even more sensible default would be to output to a subdirectory of the working directory.

**Comment by mander76** [comment]
The main reason we use it inside the esmini framework is that it has premade catalogs (both vehicles, controllers) and a bunch of roads, for rapid prototyping. Then instead you have to either set the path to those catalogs in the scenario or copy that resource folder.
