### ISSUE TITLE
Can we consider supporting the attributes of tunnel within XODR

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#180]

**Comment by mander76** [comment]
Technically it shouldn't be a problem. There are a bunch of objects that could be added similarly I guess.. @jakobkaths  have you worked with Tunnels or Bridges?

**Comment by jakobkaths** [comment]
Yes, we generate a different geometry when the bridge attribute is available. Tunnel we currently do not consider. Shouldn't be a big issue, but I'm on vacation for the next two weeks. I could have a look after.

**Comment by alexanderbukk** [comment]
@dongfeng2134 Your feature request has been implemented and there is currently a pull request availble #203. Do you have time to review it before we merge it?

**Comment by alexanderbukk** [comment]
Pull request #203 merged. Closing Issue.
