### ISSUE TITLE
How to link one lane between the roads

### ISSUE THREAD

**Issue by jiaoL06** [pyoscx/scenariogeneration#189]
How to connect the front and back relationships of the current blue road，the road can connect by function road1.add_successor(xodr.ElementType.road, road2_id, xodr.ContactPoint.start), but the lanes can not connect by xodr.create_lane_links_from_ids(road1,road2,[-1],[-1]), 

![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/1d775a99-81db-401e-b8c0-5a06a0cc454f)
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/db25d9d2-44eb-407c-8f08-f0ddf08885d4)

**Comment by mander76** [comment]
There is a long discussion about linking here:
https://github.com/pyoscx/scenariogeneration/issues/172

https://github.com/pyoscx/scenariogeneration/issues/172#issuecomment-1704645695 this one might help?

**Comment by jiaoL06** [comment]
What does the laneoffset mean？
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/3cef4275-dc22-4b2a-bf31-8de170a690e8)
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/599fcb11-dce4-4b40-b6bd-1f21797aafda)

**Comment by mander76** [comment]
basically how many lanes you want to move your connection, so as it looks in your case, that should be 0 (since -1 goes to -1), 
If you had -1 -> -2 the offset would be -1 and 1

**Comment by jiaoL06** [comment]
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/b6010f78-5a99-485f-9d69-e923602b00b3)
Referencing this method to generate link connecting_road lanes, but not take effect,the connecting_road not lane link

**Comment by mander76** [comment]
can you post your example, or a simplistic example that replicates the issue?

**Comment by jiaoL06** [comment]
Road generation methods are different from example：
`from scenariogeneration import xodr
import numpy as np
import os

roads = []

# Create junction
junction = xodr.Junction("junction_id_3", 3)

# Create roads
planview = xodr.PlanView()
planview.add_fixed_geometry(xodr.Line(100), 0.0,0.0, np.pi)
planview.adjust_geometries()
centerlane = xodr.Lane(a=2)
lanesec = xodr.LaneSection(0, centerlane)
for i in range(3):
    lane = xodr.Lane(a=3)
    lanesec.add_left_lane(lane)
lanes = xodr.Lanes()
lanes.add_lanesection(lanesec)
incoming_road = xodr.Road(0, planview, lanes)
roads.append(incoming_road)
"""
outgoing_road = xodr.create_road(xodr.Line(100),id=1,left_lanes=0,right_lanes=3)
outgoing_road.planview.set_start_point(7.0,7.0,np.pi/2)
outgoing_road.planview.adjust_geometries()
roads.append(outgoing_road)
"""
planview = xodr.PlanView()
planview.add_fixed_geometry(xodr.Arc(1/13.0,angle=np.pi/2), 0.0,-6.0, .0)
planview.adjust_geometries()
centerlane = xodr.Lane(a=2)
lanesec = xodr.LaneSection(0, centerlane)
for i in range(1):
    lane = xodr.Lane(a=3)
    lanesec.add_right_lane(lane)
lanes = xodr.Lanes()
lanes.add_lanesection(lanesec)
connecting_road = xodr.Road(2, planview, lanes)
roads.append(connecting_road)

# Successors and predecessors on road level
incoming_road.add_predecessor(xodr.ElementType.junction, 3)
#outgoing_road.add_predecessor(xodr.ElementType.junction, 3)

connecting_road.add_predecessor(xodr.ElementType.road, 0, xodr.ContactPoint.start,2) # change offset here
#connecting_road.add_successor(xodr.ElementType.road, 1, xodr.ContactPoint.start,-2) # change offset here

# Incoming junction connection
connection_1 = xodr.Connection(0, 2, xodr.ContactPoint.start)
connection_1.add_lanelink(3, -1)
junction.add_connection(connection_1)
"""
# "Outgoing" junction connection
connection_2 = xodr.Connection(1, 2, xodr.ContactPoint.end)
connection_2.add_lanelink(-1, -3)
junction.add_connection(connection_2)
"""
# Create the road lane links
# xodr.create_lane_links_from_ids(incoming_road, connecting_road, [3], [-1])
# xodr.create_lane_links_from_ids(connecting_road, outgoing_road, [-1], [-3])
xodr.create_lane_links(incoming_road, connecting_road) # change here
#xodr.create_lane_links(connecting_road, outgoing_road) # change here
# Create the OpenDRIVE
odr = xodr.OpenDrive("myroadnetwork")
odr.add_road(incoming_road)
#odr.add_road(outgoing_road)
odr.add_road(connecting_road)
odr.add_junction(junction)

# Write the OpenDRIVE file as xodr using current script name
odr.write_xml(os.path.basename(__file__).replace(".py", ".xodr"))
exit()
# Display the road network using esmini's odrviewer tool
from scenariogeneration import esmini
esmini(odr,os.path.join('/opt/esmini'))`

**Comment by jiaoL06** [comment]
Road generation methods are different：
`from scenariogeneration import xodr
import numpy as np
import os

roads = []

# Create junction
junction = xodr.Junction("junction_id_3", 3)

# Create road
planview = xodr.PlanView()
planview.add_fixed_geometry(xodr.Line(100), 0.0,0.0, np.pi)
planview.adjust_geometries()
centerlane = xodr.Lane(a=2)
lanesec = xodr.LaneSection(0, centerlane)
for i in range(3):
    lane = xodr.Lane(a=3)
    lanesec.add_left_lane(lane)
lanes = xodr.Lanes()
lanes.add_lanesection(lanesec)
incoming_road = xodr.Road(0, planview, lanes)
roads.append(incoming_road)
# Create road
planview = xodr.PlanView()
planview.add_fixed_geometry(xodr.Arc(1/13.0,angle=np.pi/2), 0.0,-6.0, .0)
planview.adjust_geometries()
centerlane = xodr.Lane(a=2)
lanesec = xodr.LaneSection(0, centerlane)
for i in range(1):
    lane = xodr.Lane(a=3)
    lanesec.add_right_lane(lane)
lanes = xodr.Lanes()
lanes.add_lanesection(lanesec)
connecting_road = xodr.Road(2, planview, lanes)
roads.append(connecting_road)

# Successors and predecessors on road level
incoming_road.add_predecessor(xodr.ElementType.junction, 3)

connecting_road.add_predecessor(xodr.ElementType.road, 0, xodr.ContactPoint.start,2) # change offset here

# Incoming junction connection
connection_1 = xodr.Connection(0, 2, xodr.ContactPoint.start)
connection_1.add_lanelink(3, -1)
junction.add_connection(connection_1)
# Create the road lane links
xodr.create_lane_links(incoming_road, connecting_road) # change here
# Create the OpenDRIVE
odr = xodr.OpenDrive("myroadnetwork")
odr.add_road(incoming_road)
odr.add_road(connecting_road)
odr.add_junction(junction)

# Write the OpenDRIVE file as xodr using current script name
odr.write_xml(os.path.basename(__file__).replace(".py", ".xodr"))
exit()
# Display the road network using esmini's odrviewer tool
from scenariogeneration import esmini
esmini(odr,os.path.join('/opt/esmini'))
`

**Comment by jiaoL06** [comment]
Road generation methods are different：
```
from scenariogeneration import xodr
import numpy as np
import os

roads = []

# Create junction
junction = xodr.Junction("junction_id_3", 3)

# Create road0
planview = xodr.PlanView()
planview.add_fixed_geometry(xodr.Line(100), 0.0,0.0, np.pi)
planview.adjust_geometries()
centerlane = xodr.Lane(a=2)
lanesec = xodr.LaneSection(0, centerlane)
for i in range(3):
    lane = xodr.Lane(a=3)
    lanesec.add_left_lane(lane)
lanes = xodr.Lanes()
lanes.add_lanesection(lanesec)
incoming_road = xodr.Road(0, planview, lanes)
roads.append(incoming_road)
##Create road2
planview = xodr.PlanView()
planview.add_fixed_geometry(xodr.Arc(1/13.0,angle=np.pi/2), 0.0,-6.0, .0)
planview.adjust_geometries()
centerlane = xodr.Lane(a=2)
lanesec = xodr.LaneSection(0, centerlane)
for i in range(1):
    lane = xodr.Lane(a=3)
    lanesec.add_right_lane(lane)
lanes = xodr.Lanes()
lanes.add_lanesection(lanesec)
connecting_road = xodr.Road(2, planview, lanes)
roads.append(connecting_road)

# Successors and predecessors on road level
incoming_road.add_predecessor(xodr.ElementType.junction, 3)
connecting_road.add_predecessor(xodr.ElementType.road, 0, xodr.ContactPoint.start,2) # change offset here

# Incoming junction connection
connection_1 = xodr.Connection(0, 2, xodr.ContactPoint.start)
connection_1.add_lanelink(3, -1)
junction.add_connection(connection_1)

xodr.create_lane_links(incoming_road, connecting_road) # change here
# Create the OpenDRIVE
odr = xodr.OpenDrive("myroadnetwork")
odr.add_road(incoming_road)
odr.add_road(connecting_road)
odr.add_junction(junction)

# Write the OpenDRIVE file as xodr using current script name
odr.write_xml(os.path.basename(__file__).replace(".py", ".xodr"))
```

**Comment by jiaoL06** [comment]
Why does this function in here（xodr.create_lane_links） not generate lane link for road. @mander76

**Comment by mander76** [comment]
There is but one little thing to add
`connecting_road = xodr.Road(2, planview, lanes,road_type=3)`
(I know the naming convention is bad)
But this will connect the road to the junction and then it knows how to do the links properly.

**Comment by jiaoL06** [comment]
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/c2db05bf-0cf4-474d-a575-71401a7ea6ba)
I found a problem in links.py.if the connected_road doesn't have the predecessor,it will be error。
If the order of these two conditions is swapped, the above example will report an error：
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/0e062dfa-2167-4368-a988-28a2bc46c289)

**Comment by jiaoL06** [comment]
> There is but one little thing to add `connecting_road = xodr.Road(2, planview, lanes,road_type=3)` (I know the naming convention is bad) But this will connect the road to the junction and then it knows how to do the links properly.

This reply is very useful。

**Comment by mander76** [comment]
Hmm, well yes, but a connecting road needs both a successor and a predecessor, if a road has no connection it should be a normal road

**Comment by jiaoL06** [comment]
we won't be able to connect and cut off the intersection like this:
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/2fd288f9-d3f9-4edc-bf5b-b25451b8959e)

**Comment by jiaoL06** [comment]
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/4af9c642-d059-4c67-ac33-e6f1c5ba76e6)
After this modification, it's all right。

**Comment by mander76** [comment]
Need to check the standard, but don't know if it's allowed to cut an intersection like that.. Otherwise That's an easy fix

**Comment by jiaoL06** [comment]
From standard, this is not mandatory

**Comment by mander76** [comment]
Yeah, cannot find anything about it. Can you do a pull-request of this change? :)

**Comment by jiaoL06** [comment]
My pleasure。

**Comment by jiaoL06** [comment]
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/21aba75e-8b27-4b9e-9273-8b501be38bb7)
I found that the code on Github is already correct, is it because the version I installed is older？
![image](https://github.com/pyoscx/scenariogeneration/assets/63989088/fbbf0318-3b05-4ac4-bb2c-799c37fb2966)

**Comment by mander76** [comment]
Well, that might be a solution aswell :P
There has been some updates like this over the past months

**Comment by mander76** [comment]
But yes, try upgrading to the latest version of scenariogeneration then. what is in github now should be in the latest release aswell.

**Comment by jiaoL06** [comment]
OK, thank you for your reply.
