### ISSUE TITLE
Issue with routes at Intersection

### ISSUE THREAD

**Issue by S1201149** [pyoscx/scenariogeneration#19]
Hello,
I am trying to create a scenario where ego vehicle will travel from road id "2 to 0" and Target vehicle will travel from road id "1 to 3" in python. (All roads meet at an intersection). The routes work fine with the ego vehicle and not with the target vehicle. The target vehicle is not following the specified route and disappears at the intersection. (The same route works fine when tried with ego vehicle)
Please find the attached python code. Let me know if I am missing something
Referred xodr - fabriksgatan.xodr
[synchronizedArrival.py.txt](https://github.com/pyoscx/scenariogeneration/files/6349153/synchronizedArrival.py.txt)

**Comment by mander76** [comment]
Hi 

You add the wrong action to the c1_event (you add ego_action, not c1_action)

**Comment by S1201149** [comment]
> Hi
> 
> You add the wrong action to the c1_event (you add ego_action, not c1_action)

Oops! Thanks for pointing it out.
