### ISSUE TITLE
Create junction results in 'only one successor allowed'

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#20]
I am having this issue that when I create a junction with different combinations of connected roads I am sometimes getting this error
Python: Traceback (most recent call last):
[...]
    junction_roads = xodr.create_junction_roads(incoming_roads, angles, 4, junction_id, spiral_part=0.01, arc_part=0.99)
  File "/opt/blender/2.91/python/lib/python3.7/site-packages/scenariogeneration/xodr/generators.py", line 277, in create_junction_roads
    roads[i].add_successor(ElementType.junction,junction)
  File "/opt/blender/2.91/python/lib/python3.7/site-packages/scenariogeneration/xodr/opendrive.py", line 186, in add_successor
    raise ValueError('only one successor is allowed')
ValueError: only one successor is allowed

I was wondering if it is possible to make the create_junction work with roads connected to it in any direction. We discussed previously that the order might be a problem but I was not able to observe that so far. The only limitation seems to be that one road should go into the junction and three should go out. But I don't think that this is mandatory according to the standard? I hope you have an easy answer, other wise I might have to have a look into it myself because this is quite a problematic limitation for me.

**Comment by johschmitz** [comment]
Okay I understand this a bit better now.
I guess it is necessary to replace this part in create_junction_roads()
```
        if i == 0:
            cp = ContactPoint.end
            roads[i].add_successor(ElementType.junction,junction)
        else:
            cp = ContactPoint.start
            roads[i].add_predecessor(ElementType.junction,junction)
```
with something a bit more intelligent that checks if the roads already have a successor or predecessor.
The current version seems to already not be able to handle a simple example with two junctions.

Also I am wondering if `create_junction_roads()` could reuse code from `create_junction_roads_standalone()` and it would be more intuitive if they would be called `create_junction_roads()` and `create_junction_roads_connected()` or  `create_junction_roads_linked()` and then `create_junction_road_connected()` would call `create_junction_roads()` internally and on top would create the connections/linking.

For now I am going to try to use the currently existing create_junction_roads_standalone() and see how to make the connections myself.

**Comment by mander76** [comment]
Yes, with create_junction_roads() you should not add any predecessors, that is automatic.
But with create_junction_roads_standalone() you have to add all of them yourself.

**Comment by johschmitz** [comment]
I managed to build my own working junction with the standalone generator,
yay! Will show you soon.

What I am saying though is that you might, especially in this earlier phase
where everyone expects it, think about breaking the API in these very few
places where the names are not intuitive and rename/rearrange a bit.
Especially for this case once you figure out what is the most generic and
comfortable way to deal with junctions.
For now I would imagine something modular like:

junction_roads = create_junction_roads(angles)
connect_junction_roads(junction_roads, incoming_roads)

and drop both the current

create_junction_roads() and
create_junction_roads_standalone()

**Comment by johschmitz** [comment]
I am still having issues:
I am creating this .xodr file
[export.xodr.zip](https://github.com/pyoscx/scenariogeneration/files/6386564/export.xodr.zip)
and the road and lane linking do look correct to me but odrviewer does not drive correctly on it although when I press the 'O' button the connections do look correct. Do you maybe see a mistake?
