### ISSUE TITLE
Obstacles in scenariogeneration

### ISSUE THREAD

**Issue by gost-sniper** [pyoscx/scenariogeneration#200]
Hello, 
I'm trying to write a simple scenario of a stand still car due to a rock or an obstacle but I can't find any class similar to `Vehicle` that can mimic an obstacle in this repo (the storyboard is irrelevant to me for the time being).

Thanks

**Comment by mander76** [comment]
Hi

Try MiscObject (MiscObjectCategory), there are some random objects there you can use

**Comment by gost-sniper** [comment]
Oh thank you for the prompt response
