### ISSUE TITLE
Suggest if can consider using Sourcery to improve code quality

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#215]
Just one line of instructions
sourcery review --fix .

![image](https://github.com/pyoscx/scenariogeneration/assets/31565799/658be2cb-207b-4a3b-8bea-f7f4f25f347e)

**Comment by dongfeng2134** [comment]
Or I can provide a pull request

**Comment by MandolinMicke** [comment]
Haha, not surprised about the ifs :P So many long ifs in the xodr module. 
Some places I sadly think the code will be very hard to read (especially in xodr) since there are so many different cases all the time.

But give it a try :)

**Comment by dongfeng2134** [comment]
https://github.com/pyoscx/scenariogeneration/pull/220
