### ISSUE TITLE
LogicFile filepath should be relative

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#23]
When exporting a scenario including OpenDRIVE I am ending up with an absolute .xodr file path in the .xosc.
```
    <RoadNetwork>
        <LogicFile filepath="/home/user/something/xodr/export.xodr"/>
    </RoadNetwork>
```
This is not portable and should be change to a relative file path!

**Comment by mander76** [comment]
It actually already exists, for both the generate and generate_single methods of ScenarioGeneration. 

`generate(self,generation_folder,override_parameters = None, write_relative_road_path = False)`

`generate_single(self,generation_folder, order = 'first',override_parameters = None, write_relative_road_path = False)`

However the documentation was missing for those inputs, will fix that for the next release.

**Comment by johschmitz** [comment]
Shouldn't the default be 'True' then? I think if somebody needs it absolute for his local development, then he should explicitly set it but relative should be the default case I believe!

**Comment by mander76** [comment]
I agree, documentation and change of default is fixed

e695bdc4c7489f8c140a6e0d02ac7d1ae9c45b9c
