### ISSUE TITLE
Bug in Trajectory in xosc

### ISSUE THREAD

**Issue by Yabing67** [pyoscx/scenariogeneration#251]
`    def add_shape(self, shape):
        """adds a shape to the trajectory (only the same shape can be used)

        Parameters
        ----------
        shape (Polyline, Clothoid, or Nurbs): the shape to be added to the trajectory

        """
        if not (
            isinstance(shape, Polyline)
            or isinstance(shape, Clothoid)
            or isinstance(shape, Nurbs)
        ):
            raise TypeError("shape input neither of type Polyline, Clothoid, or Nurbs")
        self.shapes = shape
        return self`

According to my nderstanding, in xosc/position.py there is a bug.
self.shapes = shape this line is not correct, self.shapes shpuld be initialized with a empty list and add_shape should add every new Trajectory shape once I use it. 

This bug prevents user to add more shapes in to one trajectory and allows only one shape

**Comment by MandolinMicke** [comment]
According to the standard as far as I can see it is only one shape per trajectory. 
If you want to mix trajectories that will require multiple follow trajectory actions following eachother.
Easiest is to add a StoryboardElementStateCondition to trigger the upcoming actions.

**Comment by Yabing67** [comment]
thanks for your answer
