### ISSUE TITLE
parse from a openscenario xml file?

### ISSUE THREAD

**Issue by fryant24** [pyoscx/scenariogeneration#28]
is there a way to parse from a openscenario xml file and get a pyoscx.Scenario instance? Because I want to modify a existed osc file. Thanks a lot.

**Comment by pyoscx** [comment]
Hi

Sadly no, I have started slightly to read catalogs (to tune scenarios to the size of a vehicle and such things) but not to do it for the full structure.. It would be a nice addition though.

**Comment by fryant24** [comment]
Thanks for the quick reply! Ok so I will use some XML lib to manipulate my osc file.
