### ISSUE TITLE
Bug in lane link creation

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#29]
Here is a minimum example with two straight roads that demonstrates a bug in the create_lane_links() and or adjust_roads_and_lanes() method where the lane links are not getting established.

[lane_link_bug.zip](https://github.com/pyoscx/scenariogeneration/files/6619115/lane_link_bug.zip)

**Comment by mander76** [comment]
I strongly suggest to remove the create_lane_links completely, this is taken care of by adjust_roads_and_lanes, and then it works as intended. 

My suggestion for a fix is to throw an exception when multiple links of the same type are being set. In your example it should be ok, but if a user is trying to attach multiple roads to one road (as predecessors) this will cause a problem for the algorithm in general.

**Comment by mander76** [comment]
Could fix this issue, but then another arose... Will need more time to check this sadly enough :(

**Comment by johschmitz** [comment]
Okay, no problem.

Questions:
1. Would it be possible to allow linking multiple times and the final output will just be the last? So it would not really matter if I call create_lane_links() multiple times and then adjust_roads_and_lanes(). Result will be the same. So the user must make sure to do the right thing. Maybe emit a warning on overwrite.
2. More important then 1.: Would it be possible to decouple adjustment of geometries and linking (clean separation of concerns)? So I would call adjust_roads_and_lane_geometries() and independently something like add_all_lane_links(). Otherwise the code is not verbose enough. It is not clear from the name that adjust_roads_and_lanes() will do linking and this will result in many unnecessary discussions and frustrated users.

You can keep the old adjust_roads_and_lanes() for some time and print a message "WARNING: adjust_roads_and_lanes() is deprecated. Please use ... instead." to help users migrate.

**Comment by mander76** [comment]
Well the decoupling is already there.. the method adjust_startpoints of OpenDrive does exactly that. then create_lane_links are doing the rest, the only difference it takes all unique road combinations, not looping over all roads twice. 

In the next commit the bug is fixed (finally found it), and it will raise a warning when multiple links are being created, but will keep the first (will just skip later ones).

**Comment by mander76** [comment]
I'll also update the documentation for some of the methods to make it clearer

**Comment by johschmitz** [comment]
I am just a fan of understandable method names so I don't like adjust_roads_and_lanes() because I can not guess what it does without reading documentation but okay I can live with it .. not a hard blocker.

But then one thing I would like to discuss which could be a blocker for some use-cases: Are you sure that keeping the first linking is a good idea? Imagine an interactive tool where the user wants to update things and then relink, wouldn't it be a more sensible default to overwrite and keep the last instead of skipping all later ones? I don't have a good feeling about this particular design decision.

**Comment by mander76** [comment]
Well, if you want to use adjust_roads_and_lanes() then what that does is neglect all you have done, and we go back to my initial point, and to remove all your manual adding of linking, and let adjust_roads_and_lanes take care of it for you. Still don't understand why you wanna do it yourself when it's already in the package..

On another note, if you have all startpoints (due to the interactive tool), and then the linking done by yourself, you technically don't need to call any method in the OpenDrive class (neither adjust_startpoints or adjust_roads_and_lanes).

**Comment by johschmitz** [comment]
I am completely fine with using one method to do everything for me, I just want to understand what it does, hence I need it to be called something like call adjust_road_and_lane_geometries_and_link_lanes() or I need it to be split into two calls with appropriate names like I suggested above. I want to be able to read my code in a month from now and still understand what happens without revisiting the documentation or this discussion. But if you don't change the name I will just put an explaining comment above that line of code to remember what it really does under the hood. Just not as elegant but I can live with it. In the end you as a maintainer need to decide how to name the API methods and I find it okay to accept your decision as long as it doesn't get too crazy ;-) Just note that I will always fight hard for good names of everything since I have seen many things go down the drain due to bad naming from the project name down to the variable names.
Remember: https://martinfowler.com/bliki/TwoHardThings.html

Regarding the linking itself I guess I misunderstood. I thought if I call create_lane_links() you will also just accept the first one but what I understand now I will be able to call it a second time and overwrite the first linking? Then it is all good.

**Comment by mander76** [comment]
Will try to make the push tomorrow,

**Comment by johschmitz** [comment]
Yay, thank you!
