### ISSUE TITLE
RelativeDistanceCondition with coordinateSystem

### ISSUE THREAD

**Issue by tmIdiada** [pyoscx/scenariogeneration#30]
Hi,

I'm implementing the ECE ALKS scenarios with scenariogeneration and I'm missing the coordinateSystem parameter in RelativeDistanceCondition, maybe this is an OpenSCENARIO v1.0 vs v1.1 issue. Like in implementation of the original ones I want also use coordinateSystem=entity, I think this is the default one, which is already used by the old version without this additional parameter. Can you confirm or decline this or give another statement? Maybe this is more a question for the esmini people?

Kind regards,

Thaddäus

**Comment by mander76** [comment]
Hi

I haven't really started the implementation of 1.1 things (some very minor things only) and is a thing I would like to implement soon. 

//Micke

**Comment by tmIdiada** [comment]
But, what is the old functionality without this attribute, does v1.1 with coordinateSystem=entity the same like v1.0 without this property? Do you know this?

**Comment by mander76** [comment]
The 1.1 integration is now on github (not on pypi, want to run some more tests). So feel free to check the differences

**Comment by tmIdiada** [comment]
Hi,
thank you a lot for the work and update. I will try to test it very soon, but my workload is currently too high for that. I expect to test it end of next week, hope you find enough other testers meanwhile and/or you are patient and can wait for my results.

Kind regards,

Thaddäus

**Comment by tmIdiada** [comment]
Hi,
I'm getting an error in RelativeLanePosition the entityRef is an integer, not string and the ET.to_string cannot handle that.
What I've also seen is: xsi:noNamespaceSchemaLocation has the value OpenSccenario.xsd <<<< 2 'c' instead of one

Kind regards,

Thaddäus
