### ISSUE TITLE
More OrderedDicts instead of default dicts?

### ISSUE THREAD

**Issue by tmIdiada** [pyoscx/scenariogeneration#31]
Hi,

I have a question if it would be possible to use more OrderedDict instead of default dict.

Especially I would be very interested in keys of initactions attribute of class Init in storyboard, so I'm interested in the ordering the entities have been defined after the scenario was created. This would also make the xosc xml more readable, if the ordering of the definitions would be conserved.

Kind reagrds,

Thaddäus

**Comment by mander76** [comment]
HI

I'm not sure I follow, do you want the Init to have the same ordering as the Entities element? or decide yourself on the Init order?

**Comment by tmIdiada** [comment]
Hi,

I hope I can make it with the follwoing more clear:

You get both features at once with the OrderedDict instead of dict here.

In the get_element method of Init you find this for loop (initactions is here a dict, i is somehow a bad choice for name in for loop, because i is here the key, so the entity name):
`# add private actions`
`for i in self.initactions:`
in case of normal dict the entity names "i" are randomly, thus with an OrderedDict here the user would define with his definitions the ordering in the final xosc file for the entities in Init.
The second advantage is, that after the scenario was created, one can access the order of the defined entities by accessing the variable scenario.storyboard.init.initactions.keys()

One could also check, if there are even more such positions in code, where a dict is accessed inside a get_element method.

Kind regards,

Thaddäus

**Comment by mander76** [comment]
Thanks for clearing it up. It sounds reasonable, will look into it.

**Comment by mander76** [comment]
According to this: https://realpython.com/python-ordereddict/
The dict in python >3.7 already have these features, hence what you need is already included in the standard dict.

**Comment by tmIdiada** [comment]
Ok, thanks a lot for the info, I currently have to use python 3.6 :-(

**Comment by tmIdiada** [comment]
Maybe you could write this info of losing user-defined sequences into the main page, that dicts and xml.ElementTree (also based on dicts for its attributes), and that the order is not preserved using python version < 3.7, which means that the final files (xosc, xodr, ...) would have another order, that maybe expected.

"Prerequisites
Been tested with Python >3.6.9"

**Comment by mander76** [comment]
Done!
