### ISSUE TITLE
Issues in generated xosc files

### ISSUE THREAD

**Issue by xcao8** [pyoscx/scenariogeneration#32]
Hi,

We got some sample xosc files from you. I attached one example file[xosc.zip](https://github.com/pyoscx/scenariogeneration/files/6823968/xosc.zip).

We are using one converter to convert the scenario from xosc format to our traffic simulator(dSPACE) format. But we found some issues that prevent us converting.

One type of issues are typos, e.g.
Row 2: xsi:noNamespaceShemaLocation  should be xsi:noNamespaceSchemaLocation=. 
Row 3: decription should be description
All the "Axels" should be "Axles"

Another type of issues are format. I am not sure this type of issues are due to the generated file or due to our converter's limitation. For example:
Row 3: date="2020-10-30 14:49:59.258806" not recognized by our converter
Row 26&27: According to our converter, "Axles" have to be "FrontAxle" and "RearAxle".

BR,
Xin

**Comment by MandolinMicke** [comment]
What version of the package are you using? Both of these I think are bugs already taken care of?
