### ISSUE TITLE
Missing lane type 'curb'

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#34]
The OpenDRIVE standard has a lane type 'curb' which can be used to model the curb stones. It seems to be missing. Could it be added? If it is straightforward (I hope so) probably I will create a pull request for this in case nobody is faster.

**Comment by johschmitz** [comment]
See https://github.com/pyoscx/scenariogeneration/pull/35

**Comment by MandolinMicke** [comment]
Probably added in a later version than the version the present enums were based on.
