### ISSUE TITLE
Unnecessary empty lines in generated catalog file

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#36]
When generating a catalog file with
    dump_to_catalog()
and then
    append_to_catalog()
there are some empty lines added to the file. See attached example.

[catalogs.zip](https://github.com/pyoscx/scenariogeneration/files/6994341/catalogs.zip)

**Comment by mander76** [comment]
Ah, yes. I have seen that... Haven't had time to fix that yet, but should fix that soon..

**Comment by mander76** [comment]
4138eb9ee8fa92b7cf4b64a0ecc84c5c438b81cd is fixing this issue.
