### ISSUE TITLE
How to switch between version 1.0 and 1.1 on the client

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#37]
OpenScenario v1.0 and v1.1
Currently just switch version in below picture, how can i switch in my client code

![image](https://user-images.githubusercontent.com/31565799/129669209-afe6485f-7214-4c95-94cc-5d39a901e8fd.png)

**Comment by mander76** [comment]
The easiest way to change is to set the osc_minor_version input in the Scenario constructor

as in the documentation
![image](https://user-images.githubusercontent.com/65649467/129669644-ba4cc851-63a6-4eb6-8cb7-fb69b56dac68.png)

**Comment by dongfeng2134** [comment]
Try to used it,  but seem not work. 
used scenariogeneration==0.5.0

![image](https://user-images.githubusercontent.com/31565799/129670731-656ee982-39ba-4b22-9f4a-6864e72531ec.png)

**Comment by mander76** [comment]
Aha, it's the catalog reader. Will look into it.

**Comment by mander76** [comment]
Found one bug there at least that I'll fix, but also realized the Catalogs have some osc-version incompatibilities.

**Comment by mander76** [comment]
New commit 11a9a40810c26c4b76d73978986ab18aad84cd91
Some small updates for the catalog reader, and catalogs can now be written in 1.0 aswell. 

Please try it out before I make a new release.
