### ISSUE TITLE
Polyline: ValueError: not enough time inputs

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#40]
When trying to create a polyline the documentation says:

    time (list of double): a list of timings for the positions (as of OpenSCENARIO V1.1 this can be empty)

However trying to create it with an empty list

    polyline = xosc.Polyline([], points)

Results in the error

    ValueError: not enough time inputs

What is the solution? How is it possible to create a trajectory that the vehicle should just follow with its current speed?

**Comment by mander76** [comment]
This is a bug. Apparently I only changed the documentation but not the code :-/ Will fix today
