### ISSUE TITLE
NameError: name 'EulerSpiral' is not defined

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#41]
After updating to version 0.5.1 I am now getting this error:
```
    junction_roads = xodr.create_junction_roads_standalone(angles, 3.75, junction_id, spiral_part=0.01, arc_part=0.99, startnum=1000+6*num_junctions, lane_width=3.75)
  File "<...>/scenariogeneration/xodr/generators.py", line 460, in create_junction_roads_standalone
    spiral = EulerSpiral.createFromLengthAndCurvature(spiral_length, STD_START_CLOTH, 1/r)
NameError: name 'EulerSpiral' is not defined
```

Is this supposed to still work or did the API change?

**Comment by mander76** [comment]
It's supposed to work, but didn't. Small bug when removing EulerSpiral..
This commit should fix it c12aa44c515d5853caf084ab49e4e435c00265a4 
Try it out and I'll fix a new release with these updates after that.
