### ISSUE TITLE
How to set time reference to None for NURBS trajectories

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#42]
I could not figure out how to set the time reference of a NURBS trajectory to None as suggested by Emil here:
https://github.com/esmini/esmini/issues/144
Setting to None seems to be supported by the standard so I guess Emil's suggestion is correct.
Is this not implemented or am I missing something (most probably)?

**Comment by johschmitz** [comment]
Okay I figured it out. There is no xosc.ReferenceContext.none but I can simply set the whole thing to a Python "None".

Looking at the standard I wonder if there should not be something like a TimeReference None enum defined:

```
<xsd:complexType name="TimeReference">
  <xsd:choice>
    <xsd:element name="None" type="None" minOccurs="0"/>
    <xsd:element name="Timing" type="Timing" minOccurs="0"/>
  </xsd:choice>
</xsd:complexType>
```

**Comment by mander76** [comment]
Well, the ReferenceContext does not have a "none" in the standard, hence why it doesn't exist in scenariogeneration. Don't wanna introduce additional elements in the enums that are pure openscenario.
On a side note: 
All None for the ReferenceContext, scale, and offset, will just tell the TimeReference class that it should not be used.
