### ISSUE TITLE
CatalogReader class hope to add external methods

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#44]
Sometimes need to read the same file many times to find different contents, which causes a waste of time. hope can load the contents at one time and then find the contents of interest through methods

![image](https://user-images.githubusercontent.com/31565799/133740487-c48f819d-f53b-4b76-a12f-279b1b6b083e.png)

**Comment by mander76** [comment]
Interesting use case. 
Could you do the parsing in the __init__ if you only need to parse it once?

**Comment by dongfeng2134** [comment]
Yes, it is a good idea to read once during initialization

**Comment by dongfeng2134** [comment]
how about this

`class CatalogReader:
    def __init__(self, catalog_filename: str, catalog_pathdir: str):
        pathfile = Path(catalog_pathdir) / f"{catalog_filename}.xosc"

        with Path(pathfile).open(mode="r", encoding="utf-8") as fp:
            loaded_catalog = ET.parse(fp)
            self.catalog = loaded_catalog.find("Catalog")

    def parse(entryname):
        for entry in catalog:
            if entry.tag == "Vehicle":
                if entry.attrib["name"] == entryname:
                    return Vehicle.parse(entry)
            elif entry.tag == "Pedestrian":
                if entry.attrib["name"] == entryname:
                    return Pedestrian.parse(entry)
            elif entry.tag == "Controller":
                if entry.attrib["name"] == entryname:
                    return Controller.parse(entry)
            elif entry.tag == "MiscObject":
                if entry.attrib["name"] == entryname:
                    return MiscObject.parse(entry)
            elif entry.tag == "Environment":
                if entry.attrib["name"] == entryname:
                    return Environment.parse(entry)
            elif entry.tag == "Maneuver":
                if entry.attrib["name"] == entryname:
                    return Maneuver.parse(entry)
            elif entry.tag == "Trajectory":
                if entry.attrib["name"] == entryname:
                    return Trajectory.parse(entry)
            elif entry.tag == "Route":
                if entry.attrib["name"] == entryname:
                    return Route.parse(entry)
            else:
                raise NotImplementedError("This catalogtype is not supported yet.")

        raise NoCatalogFoundError(
            "A catalog entry with the name "
            + catalog_reference.entryname
            + " could not be found in the given Catalog."
        )`

**Comment by mander76** [comment]
AH, now I see what you mean. 
Yes, this looks like a good idea.

**Comment by mander76** [comment]
i made a draft in a separate branch: 23223c463f6308cc464f6d431c7e3386da37da6a

does this look like what you need?

**Comment by dongfeng2134** [comment]
Yes, it's great！！！

**Comment by dongfeng2134** [comment]
By the way, how about the next release？

**Comment by mander76** [comment]
I'll try to have a new release today or tomorrow.

**Comment by mander76** [comment]
Merged and released!
