### ISSUE TITLE
Feature request: xosc file loader/parser 

### ISSUE THREAD

**Issue by changyuan79** [pyoscx/scenariogeneration#45]
Hi there, this is a great library for generating OpenScenarios. Thanks for sharing the capability!

I have a feature request - I did not see the part for parsing an XOSC file and loading into the Python classes. I could try to do that myself, but I think it should easy for you folks to add them? It seems we could just add a "parse_element" to each class (scenario, storyboard, ...)?  Please let me know if this can be added soon. Thank you!

**Comment by mander76** [comment]
Hi
Thanks for using it :) 

There has been similar requests, but this is A LOT of work. 
I have started with catalogs, but even that is quite a lot of work to take care of :( 

I agree that it would be a very nice addition, will start thinking about a structure how to do this, and it can be a community thing to do when the structure is there maybe :)

**Comment by changyuan79** [comment]
Thanks for your response. I'll wait for your updates then. Appreciate the great work!

**Comment by mander76** [comment]
Check out the latest release (0.7.0) now parsing is included.

**Comment by changyuan79** [comment]
Great, thank you for adding this feature!
