### ISSUE TITLE
Judgement if the value is None or not

### ISSUE THREAD

**Issue by t-nishi-24** [pyoscx/scenariogeneration#46]
I noticed this issue when I was using the Orientation class.  
**`Orientation(h=0)` will not be listed in the generated xosc file.**  
But, `Orientation(h=3.14)` will be listed as expected.  
So it seems that I am not using it incorrectly.  

I checked the `Orientation` class in utils.py, and it looks like the two methods, `is_filled` and `get_attributes`, are the culprits.  
The comment of `is_filled` method is:
```
is_filled check is any orientations are  set
```
In other words, "if all elements are None, return False. Otherwise, it will return True.".  

Currently coding is:  
```
if self.h or self.p or self.r or self.ref:
    return True
else:
    return False
```

But, correct coding I think is: 
```
if self.h is not None or self.p is not None or self.r is not None or self.ref is not None:
    return True
else:
    return False
```
This coding will return True even when h=0, p=None, r=None, reference=None.  

The same issue can be seen in the `get_attributes` method of the `Orientation` class.  
(Maybe other classes have the same issue.)

What are your thoughts?

**Comment by mander76** [comment]
Yes, that is a bug, I have fixed that in some classes.. Should take a review again and go through all of them and see if I can find more.. 

Thanks for the find, will try to fix it during the week.

**Comment by t-nishi-24** [comment]
Thank you for the very quick response!

**Comment by mander76** [comment]
I had time today already :)

Found it in a couple of other places aswell.
But here is the fix
bbc7bdb7c4c1ae55091d73f9cd7b7592e2aaba0d

**Comment by t-nishi-24** [comment]
Thank you for the re-fix!  
I can confirm that the fix is working as expected.  
Close this issue
