### ISSUE TITLE
New functions （parseMiscObjectCatalog） are expected to be added in the xosc_reader.py

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#48]
When we use xosc_reader.py, it involves the parsing of miscobjectcatalog, 
And we can see that there are definitions related to miscobject catalog.
Can you consider adding related parsing functions

**Comment by mander76** [comment]
The reading of the catalog is now added 91138648fe332600441c89b3828c41a23f259e7d
Will be available in the next release.

Not sure how to solve #44 more than to use the object multiple times and add it to the init... If you have ideas, reopen that issue.
