### ISSUE TITLE
Cannot use ParameterDeclaration for Entity definition

### ISSUE THREAD

**Issue by t-nishi-24** [pyoscx/scenariogeneration#50]
`BoundingBox` class in `utils.py` only accepts float types.  
https://pyoscx.github.io/scenariogeneration/xosc/utils.html#scenariogeneration.xosc.utils.BoundingBox  

This will cause an error if you try to define an Entity using `ParameterDeclaration` parameters, for example, like this.  

```xml
<Entities>
    <ScenarioObject name="Host">
        <Vehicle name="Host" vehicleCategory="car">
            <ParameterDeclarations/>
            <BoundingBox>
                <Center x="0" y="0" z="0.7"/>
                <Dimensions width="$Host_width" length="$Host_length" height="$Host_height"/>
            </BoundingBox>
            <Performance maxSpeed="180" maxDeceleration="10" maxAcceleration="10"/>
            <Axles>
                <FrontAxle maxSteering="0.5" wheelDiameter="0.8" trackWidth="1.68" positionX="2" positionZ="0.4"/>
                <RearAxle maxSteering="0.5" wheelDiameter="0.8" trackWidth="1.68" positionX="0" positionZ="0.4"/>
            </Axles>
            <Properties/>
        </Vehicle>
    </ScenarioObject>
</Entities>
```

**Comment by mander76** [comment]
Hmm, that is true.. 
This was introduced when trying to deal with parsing.. 
Will look into this

**Comment by mander76** [comment]
It should still work if you use the pypi release though right?

**Comment by t-nishi-24** [comment]
I have pip installed version 0.6.0 from pypi and am using it.    
`BoundingBox` does not accept the string type.    
(My example is written in hand code.)

**Comment by mander76** [comment]
I have made a change that will enable this,
35e5d2aae857d59582c9fbe4a5c22dcfd81e692d
We are currently working on parsing of xosc files aswell, so all will be included in the next release.

**Comment by t-nishi-24** [comment]
Thank you!  
I'll wait for the next release.
