### ISSUE TITLE
Pedestrian's model argument cannot be omitted.

### ISSUE THREAD

**Issue by t-nishi-24** [pyoscx/scenariogeneration#51]
According to ASAM, the Pedestrian model is optional.   
https://www.asam.net/static_downloads/modelDocumentation/content/Pedestrian.html  

But `model` is required in the `Pedestrian` class in `Entity.py`.  
https://pyoscx.github.io/scenariogeneration/xosc/entities.html#scenariogeneration.xosc.entities.Pedestrian

**Comment by mander76** [comment]
Nice catch, this is a miss after adding support for OSC1.1

**Comment by mander76** [comment]
Fix: 96d800627c933db33ec26a5b96c4f5a7183d68b6

will be available in the next release.

**Comment by t-nishi-24** [comment]
Thank you for quick fix!!
