### ISSUE TITLE
fix the argument error of CCRb.py in expample folder.

### ISSUE THREAD

**Issue by Ronald1995** [pyoscx/scenariogeneration#55]
when run CCRb.py，there will be an error as follows.

```python
target_action = xosc.LongitudinalDistanceAction(-kwargs['distance'],egoname,freespace=False)
TypeError: __init__() got multiple values for argument 'freespace'
```
[line where the error occurs](https://github.com/pyoscx/scenariogeneration/blob/main/examples/generator/CCRb.py#L125)

**Comment by mander76** [comment]
Thanks for the fix, some interfaces are updated and I haven't had time to go through the exampels yet.
