### ISSUE TITLE
How to control _MINOR_VERSION when use xosc_reader.py?

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#59]
Meet this problem when read PedestrianCategory
![image](https://user-images.githubusercontent.com/31565799/145781060-5f2d7bbe-fed3-47d5-9844-d6e723fc7ba7.png)

**Comment by mander76** [comment]
what is the problem?
This should be able to parse both 1.0, and 1.1?

**Comment by dongfeng2134** [comment]
i will close this, because i used version is 0.5.0, try use 0.6.0, is fine
