### ISSUE TITLE
Can we not have bounding_box in the class Fog?

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#60]
![image](https://user-images.githubusercontent.com/31565799/146867575-cc7e671f-f846-425d-b472-b63b7b6209d6.png)

![image](https://user-images.githubusercontent.com/31565799/146867626-7b5c949b-d7f9-4696-8a75-76126e380955.png)

**Comment by mander76** [comment]
7a87bb50d572eb19849dfe6f2ecafebd27ae629e
fixed, will be in the next release

**Comment by peter0365** [comment]
I can not set bounding_box to None (or not to set,in default) in 0.13.0 and 0.13.1

TypeError: bounding_box not of type BoundingBox
