### ISSUE TITLE
Generate xosc for scenario_runner CARLA 

### ISSUE THREAD

**Issue by steki555** [pyoscx/scenariogeneration#62]
Hello, 

at the moment I am using your library and its really useful and good made! I am trying to generate OpenScenario file which I want to run in CARLA scenario_runner. There are however some differences in the files between scenario_runner CARLA and esmini. Could you maybe tell me where I can change the source code so it generates the file for me correctly so to say or maybe you can adjust it? 

- The differences that I saw until now between the Esmini file and the Scenario_runner File are: 

`    <FileHeader description="my scenario" author="Stefani" revMajor="1" revMinor="1" date="2021-12-19T11:36:08.809969"/> `
    Here the "revMinor" should be set to 0 in order to work in scenario_runner

- There shouldnt be any CatalogLocations:

it should be just `<CatalogLocations/>`

- Road Network should be :
```
    <RoadNetwork>
        <LogicFile filepath="Town01"/>  
        <SceneGraphFile filepath=""/>
    </RoadNetwork>
```

-  by the `<Entities> `

It looks for esmini like this : 
```
<Entities>
       <ScenarioObject name="Ego">
            <CatalogReference catalogName="VehicleCatalog" entryName="vehicle.volkswagen.t2"/>
        </ScenarioObject>
    </Entities> 
```

and should look like this for scenario_runner: 
```
      <ScenarioObject name="ManyPedestrians_3_Car">
            <Vehicle name="vehicle.volkswagen.t2" vehicleCategory="car">
                <ParameterDeclarations/>
                <Performance maxSpeed="69.444" maxAcceleration="200" maxDeceleration="10.0"/>
                <BoundingBox>
                    <Center x="1.5" y="0.0" z="0.9"/>
                    <Dimensions width="2.1" length="4.5" height="1.8"/>
                </BoundingBox>
                <Axles>
                    <FrontAxle maxSteering="0.5" wheelDiameter="0.6" trackWidth="1.8" positionX="3.1" positionZ="0.3"/>
                    <RearAxle maxSteering="0.0" wheelDiameter="0.6" trackWidth="1.8" positionX="0.0" positionZ="0.3"/>
                </Axles>
                <Properties>
                    <Property name="type" value="ego_vehicle"/>
                </Properties>
            </Vehicle>
        </ScenarioObject>

```

When I change the mentioned differences in the xosc file then it works in scenario_runner! 
I would be really happy if you can help me with the problem.
 Thank you in advance

**Comment by MandolinMicke** [comment]
Hi

To have minor version 0, the Scenario class has an input called "osc_minor_version", which is 1 as default, just set that as 0 and it should be fine.

To have an empty CatalogLocation just don't add any catalogs to the Catalog object (don't know what CARLA covers, haven't had time to look into it)
If CARLA don't support Catalogs, just write the vehicle from scratch (check the one_action_example.py)

For the RoadNetwork I'm not sure what you mean. do you need an empty string for the SceneGraphFile?

**Comment by steki555** [comment]
Thank you for your answer!  I could actually fix my problem with using another constructor of RoadNetwork. 
`road = xosc.RoadNetwork(roadfile="Town04",scenegraph="")`

For. the entities I was able to use he the bounding box class and just add it. The following way: 
`bb = xosc.BoundingBox(2,5,1.8,2.0,0,0.9)
            fa = xosc.Axle(0.523598775598,0.8,1.68,2.98,0.4)
            ba = xosc.Axle(0.523598775598,0.8,1.68,0,0.4)
            tesla = xosc.Vehicle('vehicle.tesla.model3',xosc.VehicleCategory.car,bb,fa,ba,69,10,10)
            tesla.add_property('type','ego_vehicle')
            entities.add_scenario_object(entity_name,
                                            tesla)`
                                            
  And if I use the  empty catalog constructor its also then fine! `catalog = xosc.Catalog()` 
  Really nice library! Great work! I am using it for my bachelor thesis. Thank you:)

**Comment by MandolinMicke** [comment]
Great! Good luck :)
