### ISSUE TITLE
Proposal to use one lib handling OpenSCENARIO with esmini

### ISSUE THREAD

**Issue by tmIdiada** [pyoscx/scenariogeneration#63]
Hi,
could be that I'm wrong, but I have the feeling or made the experience that esmini and scenariogeneration are developed or supported by the same company working very close together. Why are you doing the same work twice, this means why are you not using the same lib for parsing OpenSCENARIO and OpenDRIVE like esmini? Clear esmini is C++, but python can also handle C++ code, so should be possible.

My proposal is to use one lib parsing and writing OpenSCENARIO files including OpenDRIVE (best and fastest by C or C++ code) that will used by both tools. What do you mean? In the future you will have for sure less work, must be only decided which team will do that. Earlier it was no issue, because esmini has not written xosc and scenariogeneration not parsed, but now it makes more and more sense. Maybe alrerady planned from your side.

Kind regards,

Thaddäus

**Comment by MandolinMicke** [comment]
Hi
Good point, However the parser in the different environments are not directly compatible. As of now, scenariogeneration supports the whole OSC 1.1, esmini doesn't. 

Another thing that might cause problems is the different versions (OSC 1.0 and 1.1). 
What would be a more proper thing is to use the OpenSource parsing of OSC that was created for 1.1.

**Comment by tmIdiada** [comment]
Hi,

it was more foreseen for the future when both tools should be compatible to OSC 1.1 except of the parsers. Both tools can then still be independent, they must only refer to a seperated github lib, like already happening with esmini and the OSC ALKS scenarios.

To use the OpenSource parsing makes only sense, if it can also export OSC and not only import, if so then yes it would be proper if it can be used also by C++ code.

But, all if this relies on your decisions and minds. It was only a proposal to make it easier in the future to have only one parser for export and import in one language instead of two.
