### ISSUE TITLE
AssignControllerAction is missing "OverrideControllerAction"

### ISSUE THREAD

**Issue by steki555** [pyoscx/scenariogeneration#66]
Hello! I am trying to make a scenario where I have to also add a camera. 
I get the following error: 
Reason: The content of element 'ControllerAction' is not complete. Tag 'OverrideControllerValueAction' expected.

Schema:

  <xsd:complexType xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ControllerAction">
      <xsd:all>
          <xsd:element name="AssignControllerAction" type="AssignControllerAction" />
          <xsd:element name="OverrideControllerValueAction" type="OverrideControllerValueAction" />
      </xsd:all>
  </xsd:complexType>

Instance:
 ``` <ControllerAction>
      <AssignControllerAction>
          <Controller name="Camera">
              <ParameterDeclarations />
              <Properties>
                  <Property name="module" value="simple_vehicle_control" />
                  <Property name="attach_camera" value="true" />
              </Properties>
          </Controller>
      </AssignControllerAction>
  </ControllerAction>
```

Path: /OpenSCENARIO/Storyboard/Init/Actions/Private/PrivateAction/ControllerAction

My code is the following: 
`       controller = xosc.Controller('Camera',properties)
        controller_action = xosc.AssignControllerAction(controller)
        overried_controller = xosc.OverrideControllerValueAction()
        overried_controller.set_brake(False,0)
        overried_controller.set_steeringwheel(False,0)
        overried_controller.set_gear(False,0)
        overried_controller.set_clutch(False,0)
        overried_controller.set_parkingbrake(False,0)
        init.add_init_action(ego_vehicle_name,controller_action)
        init.add_init_action(ego_vehicle_name,overried_controller)`
        
        The problem is that afterwards the xosc file should look the following : 
        `                    <PrivateAction>
                        <ControllerAction>
                            <AssignControllerAction>
                                <Controller name="Camera">
                                    <ParameterDeclarations/>
                                    <Properties>
                                        <Property name="module" value="simple_vehicle_control"/>
                                        <Property name="attach_camera" value="true"/>
                                    </Properties>
                                </Controller>
                            </AssignControllerAction> 
                                <OverrideControllerValueAction>
                                    <Throttle value="0" active="false"/>
                                    <Brake value="0" active="false"/>
                                    <Clutch value="0" active="false"/>
                                    <ParkingBrake value="0" active="false"/>
                                    <SteeringWheel value="0" active="false"/>
                                    <Gear number="0" active="false"/>
                                </OverrideControllerValueAction>
                        </ControllerAction>
                    </PrivateAction>
                </Private>`

But instead it looks like : 
           
```  <PrivateAction>
                <ControllerAction>
                    <AssignControllerAction activateLateral="true" activateLongitudinal="true">
                        <Controller name="Camera">
                            <ParameterDeclarations/>
                            <Properties>
                                <Property name="module" value="simple_vehicle_control"/>
                                <Property name="attach_camera" value="true"/>
                            </Properties>
                        </Controller>
                    </AssignControllerAction>
                </ControllerAction>
            </PrivateAction>
            <PrivateAction>
                <ControllerAction>
                    <OverrideControllerValueAction>
                        <Brake active="false" value="0.0"/>
                        <Clutch active="false" value="0.0"/>
                        <ParkingBrake active="false" value="0.0"/>
                        <SteeringWheel active="false" value="0.0"/>
                        <Gear active="false" value="0.0"/>
                    </OverrideControllerValueAction>
                </ControllerAction>
            </PrivateAction>
```
The differences are that in the second case, there are 2 PrivateActions, but actually both AssignControllerAction and OverrideControllerValueAction should be both under ControllerAction.

Thank you in advance! Did i miss something in the documentation to make this possible or the code should be changed?

**Comment by mander76** [comment]
Hmm, you are right, this I have missed in the documentation myself. Appears to be the only action that can look like this, I'll try to have a look this week. 

It's not wrong as it is (OSC wise), since you can add as many init actions as you want. 

And as a side note, the OverrideControllerValueAction should not have to be set if all are false, since that is the default behavior :)

**Comment by mander76** [comment]
Oh right you are using OSC 1.0 right? Then these things are mandatory... 

I'll try to make an implementation of this.

**Comment by steki555** [comment]
Thank you for your answer and that you are going to try to fix it :) ! Yes unfortunately they are mandatory in order to be able to use them in scenario_runner.

**Comment by steki555** [comment]
Hello, I know this is closed, but I found one more mistake. The Gear attribute, should have "number" instead of "value".

**Comment by mander76** [comment]
That is true, will fix right away

**Comment by mander76** [comment]
d51130fafa2f815e77c82982397a316d08aec276

**Comment by steki555** [comment]
Hey thank you :) Did you also put it in pip? Because i uninstalled it and then installed it again, but I still get the same error.

**Comment by mander76** [comment]
strange, I did a new installation, (v0.7.7) and I get 'number' as the new attribute?

**Comment by steki555** [comment]
hm, this is really strange, I am also on 0.7.7. atm, you still use the "set_gear" method right?

**Comment by mander76** [comment]
Ah, crap... 
I only managed to change the parsing part :( let me take care of it, sry.

**Comment by mander76** [comment]
8a5872822fc5053f441ffb3e7dc6454e806ac066
Can you try this?

**Comment by steki555** [comment]
Can you push it into pip? Sorry I somehow didn't manage to import the project from a folder...

**Comment by mander76** [comment]
I will, but working on another fix aswell, so will be later today in that case, want to bring both into a release in that case

**Comment by mander76** [comment]
otherwise just do 
pip install . --upgrade usually works for me

**Comment by steki555** [comment]
okay thanks :) I can wait, it no problem ^^

**Comment by mander76** [comment]
new release

**Comment by steki555** [comment]
Awesome! It works now :) thank you
