### ISSUE TITLE
How to add a UserData node under the object node of a road?

### ISSUE THREAD

**Issue by daigang896** [pyoscx/scenariogeneration#68]
Hello,
     How to add a UserData node under the object node of a road?

**Comment by mander76** [comment]
One part I haven't done myself, but it doesn't look like it's supported yet. 
According to the documentation it can be added to any element in OpenDrive, so that has to be fixed.

**Comment by mander76** [comment]
As a first implementation, do you just want "code" and "value" ? or do you want to add your own elements?

**Comment by mander76** [comment]
https://github.com/pyoscx/scenariogeneration/tree/userdata

**Comment by mander76** [comment]
New commit where the functionality is added to all classes.. Might be some sub-elements that are missing, but in general it should be ok now..

Can you verify that your usecase is covered?
