### ISSUE TITLE
Collision conditions for Challenger vehicles

### ISSUE THREAD

**Issue by mschneider1711** [pyoscx/scenariogeneration#70]
I am working with scenarios in which are many let's call them challenger vehicles. For example 20. I want to detect if any of them collides with the ego vehicle and only that is relevant for me. Right now I am adding as many collision condition triggers as challenger vehicles there are. However, OpenScenario offers a simpler way to do such a thing.
Is this possible with your package?

It looks like this, the important part is the `ByType type="vehicle`. I want to recreate that with the scenariogeneartion package.

>  <ConditionGroup>
                <Condition name="Collision trigger" delay="0" conditionEdge="rising">
                    <ByEntityCondition>
                        <TriggeringEntities triggeringEntitiesRule="any">
                            <EntityRef entityRef="EgoVehicle"/>
                        </TriggeringEntities>
                        <EntityCondition>
                            <CollisionCondition>
                                <ByType type="vehicle"/>
                            </CollisionCondition>
                        </EntityCondition>
                    </ByEntityCondition>
                </Condition>
            </ConditionGroup>

Right now I add 20 of this condition group for every challenger vehicle:
> <ConditionGroup>
                <Condition name="Collision trigger" delay="0" conditionEdge="rising">
                    <ByEntityCondition>
                        <TriggeringEntities triggeringEntitiesRule="any">
                            <EntityRef entityRef="EgoVehicle"/>
                        </TriggeringEntities>
                        <EntityCondition>
                            <CollisionCondition>
                                <EntityRef entityRef="ChallengingVehicle_958"/>
                            </CollisionCondition>
                        </EntityCondition>
                    </ByEntityCondition>
                </Condition>
            </ConditionGroup>
            <ConditionGroup>

**Comment by mander76** [comment]
xosc.CollisionCondition(xosc.ObjectType.vehicle)

**Comment by mschneider1711** [comment]
Thank you very much
