### ISSUE TITLE
Parsing xodr file

### ISSUE THREAD

**Issue by CuongVoThanh** [pyoscx/scenariogeneration#71]
Hi team,

I wonder that there is any function supports for parsing .xodr file? 
I need to parse .xodr for further editing.

Thanks.

**Comment by mander76** [comment]
Hi

No, not now. We would like to do it, but it require alot of work (even more than OpenSCENARIO), and is more complicated since there is a lot of automation involved. 

And since we don't support the entire OpenDRIVE it will fail quite often.

**Comment by CuongVoThanh** [comment]
Thanks for your reply.
I will close this issue. 

Please let me know if parsing function for .xodr available.
Thanks so much.
