### ISSUE TITLE
Add and remove entitiy action returns "wrong element tree"

### ISSUE THREAD

**Issue by mschneider1711** [pyoscx/scenariogeneration#75]
I am trying to use the above mentioned functions. However when I use them my osc file looks something like this:

>  <Maneuver name="Trajectory manouver vehicle_1">
                        <Event name="Remove vehilce event vehicle_1" priority="overwrite" maximumExecutionCount="1">
                            <Action name="Remove vehicle action">
                                <GlobalAction>
                                    <EntityAction entityRef="ChallengingVehicle_1">
                                        <DeleteEntityAction/>
                                    </EntityAction>
                                </GlobalAction>
                            </Action>

When I try to run this scenario I get erros. And looking into the OpenScenario standard I see a structure which looks like this:

> <Maneuver name="Trajectory manouver vehicle_897">
                        <Event name="End of track event" priority="overwrite" maximumExecutionCount="1">
                            <Action name="not visible">
                                <GlobalAction>
                                    <EntityAction>
                                        <DeleteEntityAction entityRef="ChallengingVehicle_897"/>
                                    </EntityAction>
                                </GlobalAction>
                            </Action>

I do not have issues with running this scenario now. Am I doing something wrong with my code or is there an error?
My code looks something like this for the AddEntityAction:

`add_vehicle_event = xosc.Event(f"Add vehicle event vehicle_{ID}", xosc.Priority.overwrite)`
`add_vehicle_event.add_trigger(add_vehicle_event_start_trigger)`           
`add_vehicle_action = xosc.AddEntityAction(self.entNames[ID], self.start_point_add_vehicle_dict[ID])`
 `add_vehicle_event.add_action("add vehilce action", add_vehicle_action)`
`manouver.add_event(add_vehicle_event)`

While `self.entNames[ID]` is a string of the above-shown challenger vehicles name and `self.start_point_add_vehicle_dict[ID]` is a `xosc.WorldPostion`.

Thank you for your help!

**Comment by mander76** [comment]
Might be a bug, will look into it.

**Comment by mander76** [comment]
Well, when I look in the UML model it says that the EntityAction itself has the entityRef, and DeteleEntityAction is just an empty element, so as I interpret the standard it should look like this:

```
<GlobalAction>
    <EntityAction entityRef="my_car">
        <AddEntityAction>
            <Position>
                <WorldPosition x="0.0" y="0.0"/>
            </Position>
        </AddEntityAction>
    </EntityAction>
</GlobalAction>


<GlobalAction>
    <EntityAction entityRef="my_car">
        <DeleteEntityAction/>
    </EntityAction>
</GlobalAction>
```

**Comment by mander76** [comment]
Me and Emil discussed this, and we found that it was a small bug in esmini, will be updated today or tomorrow.

**Comment by mschneider1711** [comment]
Okay thank you very much. The working example was indeed from Emil.
