### ISSUE TITLE
miss convert_bool() when parsing alongRoute="0"

### ISSUE THREAD

**Issue by mxterry** [pyoscx/scenariogeneration#76]
in xosc/triggers.py, L1109:
```
if 'alongRoute' in condition.attrib:
    alongroute = condition.attrib['alongRoute']
else:
    alongroute = True
```
It will raise an error when parsing xosc file with alongRoute="0".

Suggestion:
`alongroute = convert_bool(condition.attrib['alongRoute'])`

**Comment by mander76** [comment]
Hi

Well, the standard says a boolean, which is either "true" or "false" not 0, or 1

**Comment by mxterry** [comment]
> Well, the standard says a boolean, which is either "true" or "false" not 0, or 1

In fact, we are using the official migeration0_9_1to1_0.xslt to upgrade our old data of v0.9.1 created by VTD2019.

Plus, in some of the official examples in VTD2019, the alongRoute is set to "0", and the migeration doesn't change any values. That's why I have an xosc v1.0 with alongRoute="0".

**Comment by mander76** [comment]
Aha, well shouldn't be hard to add for the parsing atleast, will fix

**Comment by mander76** [comment]
63987b8dc7f6006116019ec6c16a884d70b92926 added

**Comment by mxterry** [comment]
> [63987b8](https://github.com/pyoscx/scenariogeneration/commit/63987b8dc7f6006116019ec6c16a884d70b92926) added

I've read the new commit, but I think that it's also should be fix by adding convert_bool() here:
https://github.com/pyoscx/scenariogeneration/blob/a32d13076b8f0386b3769e04668ae35fc3c1f8bb/scenariogeneration/xosc/triggers.py#L1109
to make the change applied.

**Comment by mander76** [comment]
Ah, true. will check that for more places

**Comment by mander76** [comment]
Check with this commit then: 85d0b13c4e139757335df39b8ca08aa2a0c80931

**Comment by mxterry** [comment]
Good work! Problem solved.
