### ISSUE TITLE
Can I specify a fixed date of the FileHeader?

### ISSUE THREAD

**Issue by bleach31** [pyoscx/scenariogeneration#78]
Is it possible to specify a fixed date for the FileHeader when generating an OpenSCENARIO file?

![image](https://user-images.githubusercontent.com/5919566/153103334-a91bd143-ca16-4501-aae2-37b06cfb2652.png)

I want to avoid Date being detected as a difference when comparing the generated OpenSCENARIO.

**Comment by mander76** [comment]
When you do comparison (with scenariogeneration) the date is not taken into account.
Or are you using a standard diff tool?

**Comment by bleach31** [comment]
Sorry, I didn't explain well.

I' m not comparing Python objects directly, I' m comparing the generated text files.

I'm using winMerge https://winmerge.org/

**Comment by mander76** [comment]
Ah ok, that shouldn't be hard to add. Will look into it.

**Comment by bleach31** [comment]
Thank you very much. I'm looking forward to it!

**Comment by mander76** [comment]
I actually found another bug when fixing this so it's good :) 
Can you try it out
c26caf236dccdfead218aab6fc94acf19fb29817

If it is waht you expected I'll put it on pipy later today

**Comment by bleach31** [comment]
this is perfect. thank you again.
![image](https://user-images.githubusercontent.com/5919566/153183870-b8908ab2-b9a3-4342-a9b9-ff919ff2d726.png)

-> 

![image](https://user-images.githubusercontent.com/5919566/153183926-09337706-d845-4382-b8a9-8b68c9e2194d.png)
