### ISSUE TITLE
Missing documentation for add_successor with direct_junction

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#81]
It seems that the documentation for adding a direction junction successor is incomplete. In particular it is unclear what the list in the argument direct_juntion should contain:

```
def add_successor(self,element_type,element_id,contact_point=None,lane_offset=0,direct_junction=[]):
    """ add_successor adds a successor link to the road
    
    Parameters
    ----------
        element_type (ElementType): type of element the linked road

        element_id (str/int): name of the linked road

        contact_point (ContactPoint): the contact point of the link

    """
```

**Comment by mander76** [comment]
Yes, good catch. Fixed and pushed. 

There a couple of examples creating these junctions aswell.
https://github.com/pyoscx/scenariogeneration/blob/main/examples/xodr/direct_junctions_exit.py
https://github.com/pyoscx/scenariogeneration/blob/main/examples/xodr/direct_junctions_entry.py
