### ISSUE TITLE
about the function "careate_junction_roads_standalone"

### ISSUE THREAD

**Issue by lyfs** [pyoscx/scenariogeneration#87]
hi~ i'm try to build a map like this
![image](https://user-images.githubusercontent.com/11625259/160611216-405116ed-8563-4fe2-973f-bd37686a36cf.png)
but the opendrive is 
![image](https://user-images.githubusercontent.com/11625259/160611527-524c9380-09e3-442b-ad2d-fcb02ff5f345.png)
 as you can see, the junction's road connection has some mistake, i think the parameter settings are incorrect.
![image](https://user-images.githubusercontent.com/11625259/160611948-ba09375c-febf-46cd-bdde-5601a5145172.png)
How do I calculate the right parameters? maybe the param "r" should be a list， not a float?

**Comment by mander76** [comment]
Interesting map :) Haven't tried anything like that myself. My first suggestion would be to create_junction_roads not the standalone thing..

**Comment by lyfs** [comment]
您好！我是飞哥的邮箱小飞，谢谢您的来信，他会尽快回复的，祝您快乐每一天！！

**Comment by lyfs** [comment]
yes, i tried to use the create_junction_roads , it have two questions:
1、This method dictates the direction of the road. 
2、I calculate the distance between the road and the junction centure, but it can't connect very well

**Comment by lyfs** [comment]
maybe， i can use the create_road to replace it ?

**Comment by mander76** [comment]
create_road only creates a normal road, so I would not suggest it. 
1. well, yes it was done for right hand traffic, (do you want left hand?)
2. the radius (r) you set is the exact radius of the junction (counted for the reference line) so it should be a perfect circle that is created

**Comment by lyfs** [comment]
![image](https://user-images.githubusercontent.com/11625259/160764145-385b010d-2b52-4d19-a17a-f87563b3648c.png)
I finished it by create normal road (spiral road), in fact, the special road connection have different arc
![image](https://user-images.githubusercontent.com/11625259/160764658-cc338a7e-c396-4ee4-89d5-219d9f98d3d6.png)

**Comment by lyfs** [comment]
and thank you very much, i'll close the issue latter, have a nice day : )

**Comment by lyfs** [comment]
by the way,I figured out the starting point and ending point, who was closest to the center of the intersection.This confirms the connection point. Eventually I connected these points to build a junction, so maybe we can create a function who only need the roads around the junction ?

**Comment by mander76** [comment]
that should be the create_junction_roads, could you share this road? would that be possible?

**Comment by lyfs** [comment]
ok,let's do  it , i'll give you a example pull request later

**Comment by lyfs** [comment]
@mander76  hi~ here we are
https://github.com/pyoscx/scenariogeneration/pull/88
