### ISSUE TITLE
Missing copyright information

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#94]
I could not discover any copyright information. Would it be possible to add it somewhere? Like in an about section of the readme or in the user documentation or in the license text or something like that?

**Comment by mander76** [comment]
Copyright? Isn't license enough?

**Comment by johschmitz** [comment]
As far as I know for the Anglo-American legal systems it is not sufficient. And the problem with open source software is that it is usually used on the whole planet.
I believe you can put something like in numpy to cover multiple authors:
`Copyright (c) 2005-2022, NumPy Developers.`
Or scipy
`Copyright (c) 2001-2002 Enthought, Inc. 2003-2022, SciPy Developers.`
So you can put main author comma scenariogeneration developers or something like that but please cross check,don't trust me on this.

**Comment by mander76** [comment]
found this one:
https://opensource.google/documentation/reference/releasing/authors
will try to fix that

**Comment by johschmitz** [comment]
That is good. I think the most important is to have this sentence somewhere:
`Copyright 2014 The [Project Name] Authors.`
AUTHORS file is good to have as well but I see it as optional since Git is kind of tracking the authors.

**Comment by MandolinMicke** [comment]
Now copyright info should be added everywhere
