### ISSUE TITLE
Unable to find the right codes for *country*, *Type*, and *subtype* arguments in *xodr.Signal* to generate traffic signals 

### ISSUE THREAD

**Issue by sanjaythakur** [pyoscx/scenariogeneration#97]
I have been to generate traffic signals at intersections through *xodr.Signal* by referencing the example of *junction_with_signals.py* located in *examples/xodr*. However when I trying using the generated xodr file, it throws warnings saying ```Signal Type R1-1 doesn't exists for this country*```.

![Screenshot from 2022-05-04 12-06-04](https://user-images.githubusercontent.com/5167647/166632982-965eae56-c7b7-4233-8d94-cde95ef44141.png)

Seems like this problem would go away if I could figure out the valid combinations of *country*, *Type*, and *subtype* values. Does anyone has any idea about how to find them out? Insight into any other method to generate traffic signs and signals would be appreciated too.

**Comment by mander76** [comment]
This is an interesting topic, that we had when implementing OSI in esmini, and connect OSI with a certain countrycode. Right now the only one existing is for german roadmarks (since it's listen in OSI)
https://github.com/esmini/esmini/blob/master/resources/traffic_signals/germany_traffic_signals.txt

**Comment by sanjaythakur** [comment]
Still unable to make the *xodr* from the script *junction_with_signals.py * work. Below are a couple of combinations I have tried so far. The *country*, *Type*, and *subtype* values are based on the information for Germany country code and types/subtypes [here](https://en.wikipedia.org/wiki/ISO_3166-2#Subdivisions_included_in_ISO_3166-1) and [here](https://github.com/esmini/esmini/blob/master/resources/traffic_signals/germany_traffic_signals.txt) respectively. 

- ```country="DE", Type="101", subtype="11"```. This throws ```Signal Type 101-11 doesn't exists for this country```.
- ```country="DE", Type="156", subtype="11"```. This throws ```Signal Type 156-11 doesn't exists for this country```.

Any idea on what I might be doing wrong or do differently.

**Comment by mander76** [comment]
Sadly no :-/ haven't worked much with signs.. Can make some checks later

**Comment by mander76** [comment]
The sign part of esmini has been updated, have you tried it out?
